//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarryEyes.Globalization {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppInitResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppInitResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarryEyes.Globalization.AppInitResources", typeof(AppInitResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Refer Microsoft KB に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgButtonBrowseMsKb {
            get {
                return ResourceManager.GetString("MsgButtonBrowseMsKb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Krile stores received status in local database.
        ///Cleaning database will improve performance and reduce disk consumption.
        ///If you enable this, Krile will cleanup old tweets in every startup.
        ///Enable it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgCleanupConfigContent {
            get {
                return ResourceManager.GetString("MsgCleanupConfigContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   As default, leave latest 100,000 records.
        ///You can change this threshold or enable/disable cleanup feature from settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgCleanupConfigExInfo {
            get {
                return ResourceManager.GetString("MsgCleanupConfigExInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet automatic cleanup is available. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgCleanupConfigInst {
            get {
                return ResourceManager.GetString("MsgCleanupConfigInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cleanup Tweets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgCleanupConfigTitle {
            get {
                return ResourceManager.GetString("MsgCleanupConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changing database path is a debug feature, you should not use this option as part of customize for daily use. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDatabasePathWarningContent {
            get {
                return ResourceManager.GetString("MsgDatabasePathWarningContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Krile may crash when you put a setting file or a database file on cloud storage (e.g. OneDrive, Dropbox). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDatabasePathWarningFooter {
            get {
                return ResourceManager.GetString("MsgDatabasePathWarningFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database path is specified explicitly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDatabasePathWarningInst {
            get {
                return ResourceManager.GetString("MsgDatabasePathWarningInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database path warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDatabasePathWarningTitle {
            get {
                return ResourceManager.GetString("MsgDatabasePathWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Krile Database Cleanup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDbCleanupFailedInst {
            get {
                return ResourceManager.GetString("MsgDbCleanupFailedInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database cleanup failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDbCleanupFailedTitle {
            get {
                return ResourceManager.GetString("MsgDbCleanupFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database optimization failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDbOptimizationFailedInst {
            get {
                return ResourceManager.GetString("MsgDbOptimizationFailedInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Krile Database Optimization に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDbOptimizationFailedTitle {
            get {
                return ResourceManager.GetString("MsgDbOptimizationFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maybe designation of database path is invalid.
        ///Please examine krile.exe.config . に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDbPathInvalidContent {
            get {
                return ResourceManager.GetString("MsgDbPathInvalidContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It will cause crashing Krile or hanging up your system.
        ///Changing configuration of Windows may prevent this problem. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDesktopHeapContent {
            get {
                return ResourceManager.GetString("MsgDesktopHeapContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desktop Heap parameter is too small.
        ///Current value: {0} / Lowest recommend: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDesktopHeapInfoFormat {
            get {
                return ResourceManager.GetString("MsgDesktopHeapInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   May fall into memory shortage. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDesktopHeapInst {
            get {
                return ResourceManager.GetString("MsgDesktopHeapInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execution mode is a debug feature, you should not use this option as part of customize for daily use. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgExecModeWarningContent {
            get {
                return ResourceManager.GetString("MsgExecModeWarningContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Krile may crash when you put a setting file or a database file on cloud storage (e.g. OneDrive, Dropbox). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgExecModeWarningFooter {
            get {
                return ResourceManager.GetString("MsgExecModeWarningFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execution Mode has set as Standalone. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgExecModeWarningInst {
            get {
                return ResourceManager.GetString("MsgExecModeWarningInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execution Mode Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgExecModeWarningTitle {
            get {
                return ResourceManager.GetString("MsgExecModeWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to exit Krile? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgExitInst {
            get {
                return ResourceManager.GetString("MsgExitInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit Krile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgExitTitle {
            get {
                return ResourceManager.GetString("MsgExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please retry process or reboot Windows. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgFailGeneralProcessContent {
            get {
                return ResourceManager.GetString("MsgFailGeneralProcessContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process is not complete properly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgFailGeneralProcessInst {
            get {
                return ResourceManager.GetString("MsgFailGeneralProcessInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not create setting directory. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgFailInitConfDirContent {
            get {
                return ResourceManager.GetString("MsgFailInitConfDirContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please place Krile into other directory. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgFailInitConfDirFooterText {
            get {
                return ResourceManager.GetString("MsgFailInitConfDirFooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not create locking file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgFailInitLockContent {
            get {
                return ResourceManager.GetString("MsgFailInitLockContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please reboot Windows if problem is not solved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgFailInitLockFooter {
            get {
                return ResourceManager.GetString("MsgFailInitLockFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Krile can not run duplicated that sharing settings each other. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgFailLaunchDuplicatedContent {
            get {
                return ResourceManager.GetString("MsgFailLaunchDuplicatedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Running multiple krile needs configuring krile.exe.config.
        ///Visit official site or repository for more detail. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgFailLaunchDuplicatedExInfo {
            get {
                return ResourceManager.GetString("MsgFailLaunchDuplicatedExInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Krile is already running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgFailLaunchDuplicatedInst {
            get {
                return ResourceManager.GetString("MsgFailLaunchDuplicatedInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed starting Krile. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgFailStartInst {
            get {
                return ResourceManager.GetString("MsgFailStartInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Krile StarryEyes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgFailTitle {
            get {
                return ResourceManager.GetString("MsgFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete all and &amp;reinstall latest version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgMaintenanceCmdCleanInstall {
            get {
                return ResourceManager.GetString("MsgMaintenanceCmdCleanInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Continue starting Krile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgMaintenanceCmdContinue {
            get {
                return ResourceManager.GetString("MsgMaintenanceCmdContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete &amp;all settings and database に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgMaintenanceCmdDeleteAll {
            get {
                return ResourceManager.GetString("MsgMaintenanceCmdDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Exit after deleting all settings and database に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgMaintenanceCmdDeleteAllAndExit {
            get {
                return ResourceManager.GetString("MsgMaintenanceCmdDeleteAllAndExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Delete database に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgMaintenanceCmdDeleteDb {
            get {
                return ResourceManager.GetString("MsgMaintenanceCmdDeleteDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel and E&amp;xit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgMaintenanceCmdExit {
            get {
                return ResourceManager.GetString("MsgMaintenanceCmdExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Optimize database に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgMaintenanceCmdOptimize {
            get {
                return ResourceManager.GetString("MsgMaintenanceCmdOptimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleted data can not recover. Please backup before deletion if needed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgMaintenanceContent {
            get {
                return ResourceManager.GetString("MsgMaintenanceContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Managing data stored in Krile. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgMaintenanceInst {
            get {
                return ResourceManager.GetString("MsgMaintenanceInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maintenance Krile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgMaintenanceTitle {
            get {
                return ResourceManager.GetString("MsgMaintenanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Continue starting Krile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgRecoveryCmdContinue {
            get {
                return ResourceManager.GetString("MsgRecoveryCmdContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E&amp;xit immediately に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgRecoveryCmdExit {
            get {
                return ResourceManager.GetString("MsgRecoveryCmdExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show &amp;maintenance dialog に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgRecoveryCmdMaintenance {
            get {
                return ResourceManager.GetString("MsgRecoveryCmdMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If crash caused by temporarily problem, you can continue starting.
        ///Deleting database file or rebooting Windows will help starting Krile when problem is continue. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgRecoveryContent {
            get {
                return ResourceManager.GetString("MsgRecoveryContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maintenance Dialog can delete database or/and delete settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgRecoveryFooter {
            get {
                return ResourceManager.GetString("MsgRecoveryFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Krile had not shut down properly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgRecoveryInst {
            get {
                return ResourceManager.GetString("MsgRecoveryInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recovery your Krile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgRecoveryTitle {
            get {
                return ResourceManager.GetString("MsgRecoveryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If problem is not solved, please re-installing Krile. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgReInstallKrile {
            get {
                return ResourceManager.GetString("MsgReInstallKrile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Starting krile has failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgStartupErrorInst {
            get {
                return ResourceManager.GetString("MsgStartupErrorInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Krile Startup Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgStartupErrorTitle {
            get {
                return ResourceManager.GetString("MsgStartupErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tab information is empty.
        ///Generate default tabs? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgTabWarningContent {
            get {
                return ResourceManager.GetString("MsgTabWarningContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tab information may have been lost. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgTabWarningInst {
            get {
                return ResourceManager.GetString("MsgTabWarningInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tab Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgTabWarningTitle {
            get {
                return ResourceManager.GetString("MsgTabWarningTitle", resourceCulture);
            }
        }
    }
}
