//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM リレーションシップのメタデータ

[assembly: EdmRelationshipAttribute("KrileLocalDb", "FK_Activity_0", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(StarryEyes.Mystique.User), "Activity", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StarryEyes.Mystique.Activity), true)]
[assembly: EdmRelationshipAttribute("KrileLocalDb", "FK_Activity_1", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(StarryEyes.Mystique.User), "Activity", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StarryEyes.Mystique.Activity), true)]
[assembly: EdmRelationshipAttribute("KrileLocalDb", "FK_Activity_2", "Status", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(StarryEyes.Mystique.Status), "Activity", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StarryEyes.Mystique.Activity), true)]
[assembly: EdmRelationshipAttribute("KrileLocalDb", "FK_Entity_0", "Status", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(StarryEyes.Mystique.Status), "Entity", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StarryEyes.Mystique.Entity), true)]
[assembly: EdmRelationshipAttribute("KrileLocalDb", "FK_Status_0", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(StarryEyes.Mystique.User), "Status", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StarryEyes.Mystique.Status), true)]
[assembly: EdmRelationshipAttribute("KrileLocalDb", "FK_Status_1", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(StarryEyes.Mystique.User), "Status", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StarryEyes.Mystique.Status), true)]
[assembly: EdmRelationshipAttribute("KrileLocalDb", "FK_Status_01", "Status", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(StarryEyes.Mystique.Status), "Original", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StarryEyes.Mystique.Status), true)]

#endregion

namespace StarryEyes.Mystique
{
    #region コンテキスト
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    public partial class LocalDatabase : ObjectContext
    {
        #region コンストラクター
    
        /// <summary>
        /// アプリケーション構成ファイルの 'LocalDatabase' セクションにある接続文字列を使用して新しい LocalDatabase オブジェクトを初期化します。
        /// </summary>
        public LocalDatabase() : base("name=LocalDatabase", "LocalDatabase")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 新しい LocalDatabase オブジェクトを初期化します。
        /// </summary>
        public LocalDatabase(string connectionString) : base(connectionString, "LocalDatabase")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 新しい LocalDatabase オブジェクトを初期化します。
        /// </summary>
        public LocalDatabase(EntityConnection connection) : base(connection, "LocalDatabase")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 部分メソッド
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        public ObjectSet<Activity> Activities
        {
            get
            {
                if ((_Activities == null))
                {
                    _Activities = base.CreateObjectSet<Activity>("Activities");
                }
                return _Activities;
            }
        }
        private ObjectSet<Activity> _Activities;
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        public ObjectSet<Entity> Entities
        {
            get
            {
                if ((_Entities == null))
                {
                    _Entities = base.CreateObjectSet<Entity>("Entities");
                }
                return _Entities;
            }
        }
        private ObjectSet<Entity> _Entities;
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        public ObjectSet<Status> Status
        {
            get
            {
                if ((_Status == null))
                {
                    _Status = base.CreateObjectSet<Status>("Status");
                }
                return _Status;
            }
        }
        private ObjectSet<Status> _Status;
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion
        #region AddTo メソッド
    
        /// <summary>
        /// Activities EntitySet に新しいオブジェクトを追加するための非推奨のメソッドです。代わりに、関連付けられている ObjectSet&lt;T&gt; プロパティの .Add メソッドを使用してください。
        /// </summary>
        public void AddToActivities(Activity activity)
        {
            base.AddObject("Activities", activity);
        }
    
        /// <summary>
        /// Entities EntitySet に新しいオブジェクトを追加するための非推奨のメソッドです。代わりに、関連付けられている ObjectSet&lt;T&gt; プロパティの .Add メソッドを使用してください。
        /// </summary>
        public void AddToEntities(Entity entity)
        {
            base.AddObject("Entities", entity);
        }
    
        /// <summary>
        /// Status EntitySet に新しいオブジェクトを追加するための非推奨のメソッドです。代わりに、関連付けられている ObjectSet&lt;T&gt; プロパティの .Add メソッドを使用してください。
        /// </summary>
        public void AddToStatus(Status status)
        {
            base.AddObject("Status", status);
        }
    
        /// <summary>
        /// Users EntitySet に新しいオブジェクトを追加するための非推奨のメソッドです。代わりに、関連付けられている ObjectSet&lt;T&gt; プロパティの .Add メソッドを使用してください。
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion
    }
    

    #endregion
    
    #region エンティティ
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KrileLocalDb", Name="Activity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Activity : EntityObject
    {
        #region ファクトリ メソッド
    
        /// <summary>
        /// 新しい Activity オブジェクトを作成します。
        /// </summary>
        /// <param name="id">Id プロパティの初期値。</param>
        /// <param name="createdAt">CreatedAt プロパティの初期値。</param>
        /// <param name="activityKind">ActivityKind プロパティの初期値。</param>
        /// <param name="sourceUserId">SourceUserId プロパティの初期値。</param>
        /// <param name="targetUserId">TargetUserId プロパティの初期値。</param>
        public static Activity CreateActivity(global::System.Int64 id, global::System.DateTime createdAt, global::System.Int32 activityKind, global::System.Int64 sourceUserId, global::System.Int64 targetUserId)
        {
            Activity activity = new Activity();
            activity.Id = id;
            activity.CreatedAt = createdAt;
            activity.ActivityKind = activityKind;
            activity.SourceUserId = sourceUserId;
            activity.TargetUserId = targetUserId;
            return activity;
        }

        #endregion
        #region プリミティブ プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedAt
        {
            get
            {
                return _CreatedAt;
            }
            set
            {
                OnCreatedAtChanging(value);
                ReportPropertyChanging("CreatedAt");
                _CreatedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedAt");
                OnCreatedAtChanged();
            }
        }
        private global::System.DateTime _CreatedAt;
        partial void OnCreatedAtChanging(global::System.DateTime value);
        partial void OnCreatedAtChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ActivityKind
        {
            get
            {
                return _ActivityKind;
            }
            set
            {
                OnActivityKindChanging(value);
                ReportPropertyChanging("ActivityKind");
                _ActivityKind = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ActivityKind");
                OnActivityKindChanged();
            }
        }
        private global::System.Int32 _ActivityKind;
        partial void OnActivityKindChanging(global::System.Int32 value);
        partial void OnActivityKindChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 SourceUserId
        {
            get
            {
                return _SourceUserId;
            }
            set
            {
                OnSourceUserIdChanging(value);
                ReportPropertyChanging("SourceUserId");
                _SourceUserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SourceUserId");
                OnSourceUserIdChanged();
            }
        }
        private global::System.Int64 _SourceUserId;
        partial void OnSourceUserIdChanging(global::System.Int64 value);
        partial void OnSourceUserIdChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 TargetUserId
        {
            get
            {
                return _TargetUserId;
            }
            set
            {
                OnTargetUserIdChanging(value);
                ReportPropertyChanging("TargetUserId");
                _TargetUserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TargetUserId");
                OnTargetUserIdChanged();
            }
        }
        private global::System.Int64 _TargetUserId;
        partial void OnTargetUserIdChanging(global::System.Int64 value);
        partial void OnTargetUserIdChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> TargetStatusId
        {
            get
            {
                return _TargetStatusId;
            }
            set
            {
                OnTargetStatusIdChanging(value);
                ReportPropertyChanging("TargetStatusId");
                _TargetStatusId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TargetStatusId");
                OnTargetStatusIdChanged();
            }
        }
        private Nullable<global::System.Int64> _TargetStatusId;
        partial void OnTargetStatusIdChanging(Nullable<global::System.Int64> value);
        partial void OnTargetStatusIdChanged();

        #endregion
    
        #region ナビゲーション プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KrileLocalDb", "FK_Activity_0", "User")]
        public User SourceUser
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("KrileLocalDb.FK_Activity_0", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("KrileLocalDb.FK_Activity_0", "User").Value = value;
            }
        }
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> SourceUserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("KrileLocalDb.FK_Activity_0", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("KrileLocalDb.FK_Activity_0", "User", value);
                }
            }
        }
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KrileLocalDb", "FK_Activity_1", "User")]
        public User TargetUser
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("KrileLocalDb.FK_Activity_1", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("KrileLocalDb.FK_Activity_1", "User").Value = value;
            }
        }
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> TargetUserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("KrileLocalDb.FK_Activity_1", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("KrileLocalDb.FK_Activity_1", "User", value);
                }
            }
        }
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KrileLocalDb", "FK_Activity_2", "Status")]
        public Status TargetStatus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Status>("KrileLocalDb.FK_Activity_2", "Status").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Status>("KrileLocalDb.FK_Activity_2", "Status").Value = value;
            }
        }
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Status> TargetStatusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Status>("KrileLocalDb.FK_Activity_2", "Status");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Status>("KrileLocalDb.FK_Activity_2", "Status", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KrileLocalDb", Name="Entity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Entity : EntityObject
    {
        #region ファクトリ メソッド
    
        /// <summary>
        /// 新しい Entity オブジェクトを作成します。
        /// </summary>
        /// <param name="id">Id プロパティの初期値。</param>
        /// <param name="statusId">StatusId プロパティの初期値。</param>
        /// <param name="entityType">EntityType プロパティの初期値。</param>
        /// <param name="displayText">DisplayText プロパティの初期値。</param>
        /// <param name="originalText">OriginalText プロパティの初期値。</param>
        /// <param name="mediaUrl">MediaUrl プロパティの初期値。</param>
        /// <param name="startIndex">StartIndex プロパティの初期値。</param>
        /// <param name="endIndex">EndIndex プロパティの初期値。</param>
        public static Entity CreateEntity(global::System.Int64 id, global::System.Int64 statusId, global::System.Int32 entityType, global::System.String displayText, global::System.String originalText, global::System.String mediaUrl, global::System.Int32 startIndex, global::System.Int32 endIndex)
        {
            Entity entity = new Entity();
            entity.Id = id;
            entity.StatusId = statusId;
            entity.EntityType = entityType;
            entity.DisplayText = displayText;
            entity.OriginalText = originalText;
            entity.MediaUrl = mediaUrl;
            entity.StartIndex = startIndex;
            entity.EndIndex = endIndex;
            return entity;
        }

        #endregion
        #region プリミティブ プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 StatusId
        {
            get
            {
                return _StatusId;
            }
            set
            {
                OnStatusIdChanging(value);
                ReportPropertyChanging("StatusId");
                _StatusId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StatusId");
                OnStatusIdChanged();
            }
        }
        private global::System.Int64 _StatusId;
        partial void OnStatusIdChanging(global::System.Int64 value);
        partial void OnStatusIdChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EntityType
        {
            get
            {
                return _EntityType;
            }
            set
            {
                OnEntityTypeChanging(value);
                ReportPropertyChanging("EntityType");
                _EntityType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntityType");
                OnEntityTypeChanged();
            }
        }
        private global::System.Int32 _EntityType;
        partial void OnEntityTypeChanging(global::System.Int32 value);
        partial void OnEntityTypeChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DisplayText
        {
            get
            {
                return _DisplayText;
            }
            set
            {
                OnDisplayTextChanging(value);
                ReportPropertyChanging("DisplayText");
                _DisplayText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DisplayText");
                OnDisplayTextChanged();
            }
        }
        private global::System.String _DisplayText;
        partial void OnDisplayTextChanging(global::System.String value);
        partial void OnDisplayTextChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OriginalText
        {
            get
            {
                return _OriginalText;
            }
            set
            {
                OnOriginalTextChanging(value);
                ReportPropertyChanging("OriginalText");
                _OriginalText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OriginalText");
                OnOriginalTextChanged();
            }
        }
        private global::System.String _OriginalText;
        partial void OnOriginalTextChanging(global::System.String value);
        partial void OnOriginalTextChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MediaUrl
        {
            get
            {
                return _MediaUrl;
            }
            set
            {
                OnMediaUrlChanging(value);
                ReportPropertyChanging("MediaUrl");
                _MediaUrl = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MediaUrl");
                OnMediaUrlChanged();
            }
        }
        private global::System.String _MediaUrl;
        partial void OnMediaUrlChanging(global::System.String value);
        partial void OnMediaUrlChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StartIndex
        {
            get
            {
                return _StartIndex;
            }
            set
            {
                OnStartIndexChanging(value);
                ReportPropertyChanging("StartIndex");
                _StartIndex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartIndex");
                OnStartIndexChanged();
            }
        }
        private global::System.Int32 _StartIndex;
        partial void OnStartIndexChanging(global::System.Int32 value);
        partial void OnStartIndexChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EndIndex
        {
            get
            {
                return _EndIndex;
            }
            set
            {
                OnEndIndexChanging(value);
                ReportPropertyChanging("EndIndex");
                _EndIndex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndIndex");
                OnEndIndexChanged();
            }
        }
        private global::System.Int32 _EndIndex;
        partial void OnEndIndexChanging(global::System.Int32 value);
        partial void OnEndIndexChanged();

        #endregion
    
        #region ナビゲーション プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KrileLocalDb", "FK_Entity_0", "Status")]
        public Status Status
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Status>("KrileLocalDb.FK_Entity_0", "Status").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Status>("KrileLocalDb.FK_Entity_0", "Status").Value = value;
            }
        }
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Status> StatusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Status>("KrileLocalDb.FK_Entity_0", "Status");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Status>("KrileLocalDb.FK_Entity_0", "Status", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KrileLocalDb", Name="Status")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Status : EntityObject
    {
        #region ファクトリ メソッド
    
        /// <summary>
        /// 新しい Status オブジェクトを作成します。
        /// </summary>
        /// <param name="id">Id プロパティの初期値。</param>
        /// <param name="statusType">StatusType プロパティの初期値。</param>
        /// <param name="isDataLacking">IsDataLacking プロパティの初期値。</param>
        /// <param name="userId">UserId プロパティの初期値。</param>
        /// <param name="text">Text プロパティの初期値。</param>
        /// <param name="createdAt">CreatedAt プロパティの初期値。</param>
        /// <param name="isFavored">IsFavored プロパティの初期値。</param>
        /// <param name="source">Source プロパティの初期値。</param>
        public static Status CreateStatus(global::System.Int64 id, global::System.Int32 statusType, global::System.Boolean isDataLacking, global::System.Int64 userId, global::System.String text, global::System.DateTime createdAt, global::System.Boolean isFavored, global::System.String source)
        {
            Status status = new Status();
            status.Id = id;
            status.StatusType = statusType;
            status.IsDataLacking = isDataLacking;
            status.UserId = userId;
            status.Text = text;
            status.CreatedAt = createdAt;
            status.IsFavored = isFavored;
            status.Source = source;
            return status;
        }

        #endregion
        #region プリミティブ プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StatusType
        {
            get
            {
                return _StatusType;
            }
            set
            {
                OnStatusTypeChanging(value);
                ReportPropertyChanging("StatusType");
                _StatusType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StatusType");
                OnStatusTypeChanged();
            }
        }
        private global::System.Int32 _StatusType;
        partial void OnStatusTypeChanging(global::System.Int32 value);
        partial void OnStatusTypeChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsDataLacking
        {
            get
            {
                return _IsDataLacking;
            }
            set
            {
                OnIsDataLackingChanging(value);
                ReportPropertyChanging("IsDataLacking");
                _IsDataLacking = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDataLacking");
                OnIsDataLackingChanged();
            }
        }
        private global::System.Boolean _IsDataLacking;
        partial void OnIsDataLackingChanging(global::System.Boolean value);
        partial void OnIsDataLackingChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int64 _UserId;
        partial void OnUserIdChanging(global::System.Int64 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedAt
        {
            get
            {
                return _CreatedAt;
            }
            set
            {
                OnCreatedAtChanging(value);
                ReportPropertyChanging("CreatedAt");
                _CreatedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedAt");
                OnCreatedAtChanged();
            }
        }
        private global::System.DateTime _CreatedAt;
        partial void OnCreatedAtChanging(global::System.DateTime value);
        partial void OnCreatedAtChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsFavored
        {
            get
            {
                return _IsFavored;
            }
            set
            {
                OnIsFavoredChanging(value);
                ReportPropertyChanging("IsFavored");
                _IsFavored = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsFavored");
                OnIsFavoredChanged();
            }
        }
        private global::System.Boolean _IsFavored;
        partial void OnIsFavoredChanging(global::System.Boolean value);
        partial void OnIsFavoredChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Source
        {
            get
            {
                return _Source;
            }
            set
            {
                OnSourceChanging(value);
                ReportPropertyChanging("Source");
                _Source = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Source");
                OnSourceChanged();
            }
        }
        private global::System.String _Source;
        partial void OnSourceChanging(global::System.String value);
        partial void OnSourceChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> InReplyToStatusId
        {
            get
            {
                return _InReplyToStatusId;
            }
            set
            {
                OnInReplyToStatusIdChanging(value);
                ReportPropertyChanging("InReplyToStatusId");
                _InReplyToStatusId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InReplyToStatusId");
                OnInReplyToStatusIdChanged();
            }
        }
        private Nullable<global::System.Int64> _InReplyToStatusId;
        partial void OnInReplyToStatusIdChanging(Nullable<global::System.Int64> value);
        partial void OnInReplyToStatusIdChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> InReplyToUserId
        {
            get
            {
                return _InReplyToUserId;
            }
            set
            {
                OnInReplyToUserIdChanging(value);
                ReportPropertyChanging("InReplyToUserId");
                _InReplyToUserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InReplyToUserId");
                OnInReplyToUserIdChanged();
            }
        }
        private Nullable<global::System.Int64> _InReplyToUserId;
        partial void OnInReplyToUserIdChanging(Nullable<global::System.Int64> value);
        partial void OnInReplyToUserIdChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InReplyToScreenName
        {
            get
            {
                return _InReplyToScreenName;
            }
            set
            {
                OnInReplyToScreenNameChanging(value);
                ReportPropertyChanging("InReplyToScreenName");
                _InReplyToScreenName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InReplyToScreenName");
                OnInReplyToScreenNameChanged();
            }
        }
        private global::System.String _InReplyToScreenName;
        partial void OnInReplyToScreenNameChanging(global::System.String value);
        partial void OnInReplyToScreenNameChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> RetweetedOriginalId
        {
            get
            {
                return _RetweetedOriginalId;
            }
            set
            {
                OnRetweetedOriginalIdChanging(value);
                ReportPropertyChanging("RetweetedOriginalId");
                _RetweetedOriginalId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RetweetedOriginalId");
                OnRetweetedOriginalIdChanged();
            }
        }
        private Nullable<global::System.Int64> _RetweetedOriginalId;
        partial void OnRetweetedOriginalIdChanging(Nullable<global::System.Int64> value);
        partial void OnRetweetedOriginalIdChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private Nullable<global::System.Single> _Latitude;
        partial void OnLatitudeChanging(Nullable<global::System.Single> value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> RecipientId
        {
            get
            {
                return _RecipientId;
            }
            set
            {
                OnRecipientIdChanging(value);
                ReportPropertyChanging("RecipientId");
                _RecipientId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecipientId");
                OnRecipientIdChanged();
            }
        }
        private Nullable<global::System.Int64> _RecipientId;
        partial void OnRecipientIdChanging(Nullable<global::System.Int64> value);
        partial void OnRecipientIdChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private Nullable<global::System.Single> _Longitude;
        partial void OnLongitudeChanging(Nullable<global::System.Single> value);
        partial void OnLongitudeChanged();

        #endregion
    
        #region ナビゲーション プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KrileLocalDb", "FK_Activity_2", "Activity")]
        public EntityCollection<Activity> Activities
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Activity>("KrileLocalDb.FK_Activity_2", "Activity");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Activity>("KrileLocalDb.FK_Activity_2", "Activity", value);
                }
            }
        }
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KrileLocalDb", "FK_Entity_0", "Entity")]
        public EntityCollection<Entity> Entities
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Entity>("KrileLocalDb.FK_Entity_0", "Entity");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Entity>("KrileLocalDb.FK_Entity_0", "Entity", value);
                }
            }
        }
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KrileLocalDb", "FK_Status_0", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("KrileLocalDb.FK_Status_0", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("KrileLocalDb.FK_Status_0", "User").Value = value;
            }
        }
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("KrileLocalDb.FK_Status_0", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("KrileLocalDb.FK_Status_0", "User", value);
                }
            }
        }
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KrileLocalDb", "FK_Status_1", "User")]
        public User Recipient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("KrileLocalDb.FK_Status_1", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("KrileLocalDb.FK_Status_1", "User").Value = value;
            }
        }
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> RecipientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("KrileLocalDb.FK_Status_1", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("KrileLocalDb.FK_Status_1", "User", value);
                }
            }
        }
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KrileLocalDb", "FK_Status_01", "Original")]
        public EntityCollection<Status> Retweets
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Status>("KrileLocalDb.FK_Status_01", "Original");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Status>("KrileLocalDb.FK_Status_01", "Original", value);
                }
            }
        }
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KrileLocalDb", "FK_Status_01", "Status")]
        public Status RetweetedOriginal
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Status>("KrileLocalDb.FK_Status_01", "Status").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Status>("KrileLocalDb.FK_Status_01", "Status").Value = value;
            }
        }
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Status> RetweetedOriginalReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Status>("KrileLocalDb.FK_Status_01", "Status");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Status>("KrileLocalDb.FK_Status_01", "Status", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KrileLocalDb", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region ファクトリ メソッド
    
        /// <summary>
        /// 新しい User オブジェクトを作成します。
        /// </summary>
        /// <param name="id">Id プロパティの初期値。</param>
        /// <param name="screenName">ScreenName プロパティの初期値。</param>
        /// <param name="isDataLacking">IsDataLacking プロパティの初期値。</param>
        /// <param name="name">Name プロパティの初期値。</param>
        /// <param name="description">Description プロパティの初期値。</param>
        /// <param name="location">Location プロパティの初期値。</param>
        /// <param name="url">Url プロパティの初期値。</param>
        /// <param name="profileImageUri">ProfileImageUri プロパティの初期値。</param>
        /// <param name="isProtected">IsProtected プロパティの初期値。</param>
        /// <param name="isVerified">IsVerified プロパティの初期値。</param>
        /// <param name="isTranslator">IsTranslator プロパティの初期値。</param>
        /// <param name="isContributorsEnabled">IsContributorsEnabled プロパティの初期値。</param>
        /// <param name="isGeoEnabled">IsGeoEnabled プロパティの初期値。</param>
        /// <param name="statusesCount">StatusesCount プロパティの初期値。</param>
        /// <param name="friendsCount">FriendsCount プロパティの初期値。</param>
        /// <param name="followersCount">FollowersCount プロパティの初期値。</param>
        /// <param name="favoritesCount">FavoritesCount プロパティの初期値。</param>
        /// <param name="listedCount">ListedCount プロパティの初期値。</param>
        /// <param name="language">Language プロパティの初期値。</param>
        /// <param name="createdAt">CreatedAt プロパティの初期値。</param>
        public static User CreateUser(global::System.Int64 id, global::System.String screenName, global::System.Boolean isDataLacking, global::System.String name, global::System.String description, global::System.String location, global::System.String url, global::System.String profileImageUri, global::System.Boolean isProtected, global::System.Boolean isVerified, global::System.Boolean isTranslator, global::System.Boolean isContributorsEnabled, global::System.Boolean isGeoEnabled, global::System.Int64 statusesCount, global::System.Int64 friendsCount, global::System.Int64 followersCount, global::System.Int64 favoritesCount, global::System.Int64 listedCount, global::System.String language, global::System.DateTime createdAt)
        {
            User user = new User();
            user.Id = id;
            user.ScreenName = screenName;
            user.IsDataLacking = isDataLacking;
            user.Name = name;
            user.Description = description;
            user.Location = location;
            user.Url = url;
            user.ProfileImageUri = profileImageUri;
            user.IsProtected = isProtected;
            user.IsVerified = isVerified;
            user.IsTranslator = isTranslator;
            user.IsContributorsEnabled = isContributorsEnabled;
            user.IsGeoEnabled = isGeoEnabled;
            user.StatusesCount = statusesCount;
            user.FriendsCount = friendsCount;
            user.FollowersCount = followersCount;
            user.FavoritesCount = favoritesCount;
            user.ListedCount = listedCount;
            user.Language = language;
            user.CreatedAt = createdAt;
            return user;
        }

        #endregion
        #region プリミティブ プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ScreenName
        {
            get
            {
                return _ScreenName;
            }
            set
            {
                OnScreenNameChanging(value);
                ReportPropertyChanging("ScreenName");
                _ScreenName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ScreenName");
                OnScreenNameChanged();
            }
        }
        private global::System.String _ScreenName;
        partial void OnScreenNameChanging(global::System.String value);
        partial void OnScreenNameChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsDataLacking
        {
            get
            {
                return _IsDataLacking;
            }
            set
            {
                OnIsDataLackingChanging(value);
                ReportPropertyChanging("IsDataLacking");
                _IsDataLacking = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDataLacking");
                OnIsDataLackingChanged();
            }
        }
        private global::System.Boolean _IsDataLacking;
        partial void OnIsDataLackingChanging(global::System.Boolean value);
        partial void OnIsDataLackingChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProfileImageUri
        {
            get
            {
                return _ProfileImageUri;
            }
            set
            {
                OnProfileImageUriChanging(value);
                ReportPropertyChanging("ProfileImageUri");
                _ProfileImageUri = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProfileImageUri");
                OnProfileImageUriChanged();
            }
        }
        private global::System.String _ProfileImageUri;
        partial void OnProfileImageUriChanging(global::System.String value);
        partial void OnProfileImageUriChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsProtected
        {
            get
            {
                return _IsProtected;
            }
            set
            {
                OnIsProtectedChanging(value);
                ReportPropertyChanging("IsProtected");
                _IsProtected = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsProtected");
                OnIsProtectedChanged();
            }
        }
        private global::System.Boolean _IsProtected;
        partial void OnIsProtectedChanging(global::System.Boolean value);
        partial void OnIsProtectedChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsVerified
        {
            get
            {
                return _IsVerified;
            }
            set
            {
                OnIsVerifiedChanging(value);
                ReportPropertyChanging("IsVerified");
                _IsVerified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsVerified");
                OnIsVerifiedChanged();
            }
        }
        private global::System.Boolean _IsVerified;
        partial void OnIsVerifiedChanging(global::System.Boolean value);
        partial void OnIsVerifiedChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsTranslator
        {
            get
            {
                return _IsTranslator;
            }
            set
            {
                OnIsTranslatorChanging(value);
                ReportPropertyChanging("IsTranslator");
                _IsTranslator = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsTranslator");
                OnIsTranslatorChanged();
            }
        }
        private global::System.Boolean _IsTranslator;
        partial void OnIsTranslatorChanging(global::System.Boolean value);
        partial void OnIsTranslatorChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsContributorsEnabled
        {
            get
            {
                return _IsContributorsEnabled;
            }
            set
            {
                OnIsContributorsEnabledChanging(value);
                ReportPropertyChanging("IsContributorsEnabled");
                _IsContributorsEnabled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsContributorsEnabled");
                OnIsContributorsEnabledChanged();
            }
        }
        private global::System.Boolean _IsContributorsEnabled;
        partial void OnIsContributorsEnabledChanging(global::System.Boolean value);
        partial void OnIsContributorsEnabledChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsGeoEnabled
        {
            get
            {
                return _IsGeoEnabled;
            }
            set
            {
                OnIsGeoEnabledChanging(value);
                ReportPropertyChanging("IsGeoEnabled");
                _IsGeoEnabled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsGeoEnabled");
                OnIsGeoEnabledChanged();
            }
        }
        private global::System.Boolean _IsGeoEnabled;
        partial void OnIsGeoEnabledChanging(global::System.Boolean value);
        partial void OnIsGeoEnabledChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 StatusesCount
        {
            get
            {
                return _StatusesCount;
            }
            set
            {
                OnStatusesCountChanging(value);
                ReportPropertyChanging("StatusesCount");
                _StatusesCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StatusesCount");
                OnStatusesCountChanged();
            }
        }
        private global::System.Int64 _StatusesCount;
        partial void OnStatusesCountChanging(global::System.Int64 value);
        partial void OnStatusesCountChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FriendsCount
        {
            get
            {
                return _FriendsCount;
            }
            set
            {
                OnFriendsCountChanging(value);
                ReportPropertyChanging("FriendsCount");
                _FriendsCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FriendsCount");
                OnFriendsCountChanged();
            }
        }
        private global::System.Int64 _FriendsCount;
        partial void OnFriendsCountChanging(global::System.Int64 value);
        partial void OnFriendsCountChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FollowersCount
        {
            get
            {
                return _FollowersCount;
            }
            set
            {
                OnFollowersCountChanging(value);
                ReportPropertyChanging("FollowersCount");
                _FollowersCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FollowersCount");
                OnFollowersCountChanged();
            }
        }
        private global::System.Int64 _FollowersCount;
        partial void OnFollowersCountChanging(global::System.Int64 value);
        partial void OnFollowersCountChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FavoritesCount
        {
            get
            {
                return _FavoritesCount;
            }
            set
            {
                OnFavoritesCountChanging(value);
                ReportPropertyChanging("FavoritesCount");
                _FavoritesCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FavoritesCount");
                OnFavoritesCountChanged();
            }
        }
        private global::System.Int64 _FavoritesCount;
        partial void OnFavoritesCountChanging(global::System.Int64 value);
        partial void OnFavoritesCountChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ListedCount
        {
            get
            {
                return _ListedCount;
            }
            set
            {
                OnListedCountChanging(value);
                ReportPropertyChanging("ListedCount");
                _ListedCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ListedCount");
                OnListedCountChanged();
            }
        }
        private global::System.Int64 _ListedCount;
        partial void OnListedCountChanging(global::System.Int64 value);
        partial void OnListedCountChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Language
        {
            get
            {
                return _Language;
            }
            set
            {
                OnLanguageChanging(value);
                ReportPropertyChanging("Language");
                _Language = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Language");
                OnLanguageChanged();
            }
        }
        private global::System.String _Language;
        partial void OnLanguageChanging(global::System.String value);
        partial void OnLanguageChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedAt
        {
            get
            {
                return _CreatedAt;
            }
            set
            {
                OnCreatedAtChanging(value);
                ReportPropertyChanging("CreatedAt");
                _CreatedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedAt");
                OnCreatedAtChanged();
            }
        }
        private global::System.DateTime _CreatedAt;
        partial void OnCreatedAtChanging(global::System.DateTime value);
        partial void OnCreatedAtChanged();

        #endregion
    
        #region ナビゲーション プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KrileLocalDb", "FK_Activity_0", "Activity")]
        public EntityCollection<Activity> Activities
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Activity>("KrileLocalDb.FK_Activity_0", "Activity");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Activity>("KrileLocalDb.FK_Activity_0", "Activity", value);
                }
            }
        }
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KrileLocalDb", "FK_Activity_1", "Activity")]
        public EntityCollection<Activity> ReceiptActivities
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Activity>("KrileLocalDb.FK_Activity_1", "Activity");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Activity>("KrileLocalDb.FK_Activity_1", "Activity", value);
                }
            }
        }
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KrileLocalDb", "FK_Status_0", "Status")]
        public EntityCollection<Status> Status
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Status>("KrileLocalDb.FK_Status_0", "Status");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Status>("KrileLocalDb.FK_Status_0", "Status", value);
                }
            }
        }
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KrileLocalDb", "FK_Status_1", "Status")]
        public EntityCollection<Status> ReceivedMessages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Status>("KrileLocalDb.FK_Status_1", "Status");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Status>("KrileLocalDb.FK_Status_1", "Status", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
