using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reactive.Linq;
using System.Threading;
using System.Windows;
using System.Xaml;
using StarryEyes.Albireo.Helpers;
using StarryEyes.Anomaly.TwitterApi.DataModels;
using StarryEyes.Filters;
using StarryEyes.Filters.Expressions;
using StarryEyes.Filters.Parsing;
using StarryEyes.Globalization.Models;
using StarryEyes.Models.Accounting;
using StarryEyes.Models.Subsystems.Notifications.UI;
using StarryEyes.Models.Timelines.Tabs;
using StarryEyes.Nightmare.Windows;

namespace StarryEyes.Settings
{
    public static class Setting
    {
        private static ConcurrentDictionary<string, object> _settingValueHolder;

        public static readonly SettingItem<string> AutoGeneratedUserId =
            new SettingItem<string>("AutoGeneratedUserId", String.Empty);

        public static readonly SettingItemStruct<bool> IsPowerUser =
            new SettingItemStruct<bool>("IsPowerUser", false);

        #region Tab and Columns

        private static readonly SettingItem<ColumnDescription[]> _columns =
            new SettingItem<ColumnDescription[]>("Columns", null);

        internal static IEnumerable<ColumnDescription> Columns
        {
            get { return _columns.Value ?? GenerateEmptyTabs(); }
            set { _columns.Value = value.Guard().ToArray(); }
        }

        private static IEnumerable<ColumnDescription> GenerateEmptyTabs()
        {
            return new[]
            {
                new ColumnDescription
                {
                    Tabs = new[]
                    {
                        CommonTabBuilder.GenerateGeneralTab(),
                        CommonTabBuilder.GenerateHomeTab(),
                        CommonTabBuilder.GenerateMentionTab(),
                        CommonTabBuilder.GenerateMeTab()
                    }.Select(t => new TabDescription(t)).ToArray()
                },
                new ColumnDescription
                {
                    Tabs = new[] {CommonTabBuilder.GenerateActivitiesTab()}
                        .Select(t => new TabDescription(t)).ToArray()
                }
            };
        }

        internal static void ResetTabInfo()
        {
            _columns.Value = null;
        }

        #endregion

        #region Authentication and accounts

        private static readonly SettingItem<List<TwitterAccount>> _accounts =
            new SettingItem<List<TwitterAccount>>("Accounts", new List<TwitterAccount>());

        private static AccountManager _manager;

        public static AccountManager Accounts
        {
            get { return _manager; }
        }

        public static readonly SettingItem<string> GlobalConsumerKey =
            new SettingItem<string>("GlobalConsumerKey", null);

        public static readonly SettingItem<string> GlobalConsumerSecret =
            new SettingItem<string>("GlobalConsumerSecret", null);

        #endregion

        #region Timeline display and action

        public static readonly SettingItemStruct<TweetDisplayMode> TweetDisplayMode =
            new SettingItemStruct<TweetDisplayMode>("TweetDisplayMode", Settings.TweetDisplayMode.Expanded);

        public static readonly SettingItemStruct<ScrollLockStrategy> ScrollLockStrategy =
            new SettingItemStruct<ScrollLockStrategy>("ScrollLockStrategy", Settings.ScrollLockStrategy.WhenScrolled);

        public static readonly SettingItemStruct<TimelineIconResolution> IconResolution =
            new SettingItemStruct<TimelineIconResolution>("IconResolution", TimelineIconResolution.Optimized);

        public static readonly SettingItemStruct<bool> IsAnimateScrollToNewTweet =
            new SettingItemStruct<bool>("IsAnimateScrollToNewTweet", true);

        public static readonly SettingItemStruct<bool> IsScrollByPixel =
            new SettingItemStruct<bool>("IsScrollByPixel", true);

        public static readonly SettingItemStruct<bool> AllowFavoriteMyself =
            new SettingItemStruct<bool>("AllowFavoriteMyself", false);

        public static readonly SettingItemStruct<ThumbnailMode> ThumbnailMode =
            new SettingItemStruct<ThumbnailMode>("ThumbnailMode", Settings.ThumbnailMode.All);

        public static readonly SettingItemStruct<bool> OpenTwitterImageWithOriginalSize =
            new SettingItemStruct<bool>("OpenTwitterImageWithOriginalSize", true);

        public static readonly SettingItem<string> SearchLanguage =
            new SettingItem<string>("SearchLanguage", Thread.CurrentThread.CurrentUICulture.TwoLetterISOLanguageName);

        public static readonly SettingItemStruct<bool> AutoCleanupTweets =
            new SettingItemStruct<bool>("AutoCleanupTweets", true);

        public static readonly SettingItemStruct<int> AutoCleanupThreshold =
            new SettingItemStruct<int>("AutoCleanupThreshold", -1);

        #endregion

        #region Themes and Key Assigns

        public static readonly SettingItem<string> Theme =
            new SettingItem<string>("Theme", null);

        public static readonly SettingItem<string> BackgroundImagePath =
            new SettingItem<string>("BackgroundImagePath", null);

        public static readonly SettingItemStruct<int> BackgroundImageTransparency =
            new SettingItemStruct<int>("BackgroundImageTransparency", 0);

        public static readonly SettingItem<string> KeyAssign =
            new SettingItem<string>("KeyAssign", null);

        #endregion

        #region Mutes

        public static readonly FilterSettingItem Muteds = new FilterSettingItem("Muteds");

        public static readonly SettingItemStruct<bool> MuteBlockingUsers =
            new SettingItemStruct<bool>("MuteBlockingUsers", true);

        public static readonly SettingItemStruct<bool> MuteNoRetweets =
            new SettingItemStruct<bool>("MuteNoRetweets", true);

        public static readonly SettingItemStruct<bool> MuteOfficialMutes =
            new SettingItemStruct<bool>("MuteOfficialMutes", true);

        public static readonly SettingItemStruct<bool> UseLightweightMute =
            new SettingItemStruct<bool>("UseLightweightMute", false);

        #endregion

        #region Input control

        public static readonly SettingItemStruct<bool> IsUrlAutoEscapeEnabled =
            new SettingItemStruct<bool>("IsUrlAutoEscapeEnabled", false);

        public static readonly SettingItemStruct<bool> IsInputSuggestEnabled =
            new SettingItemStruct<bool>("IsInputSuggestEnabled", true);

        public static readonly SettingItemStruct<InputUserSuggestMode> InputUserSuggestMode =
            new SettingItemStruct<InputUserSuggestMode>("InputUserSuggestMode",
                Settings.InputUserSuggestMode.RelatedOnly);

        public static readonly SettingItemStruct<bool> WarnAmending =
            new SettingItemStruct<bool>("WarnAmending", true);

        public static readonly SettingItemStruct<bool> SuppressTagBindingInReply =
            new SettingItemStruct<bool>("SuppresTagBindingInReply", true);

        public static readonly SettingItemStruct<bool> WarnReplyFromThirdAccount =
            new SettingItemStruct<bool>("WarnReplyFromThirdAccount", true);

        public static readonly SettingItemStruct<TweetBoxClosingAction> TweetBoxClosingAction =
            new SettingItemStruct<TweetBoxClosingAction>("TweetBoxClosingAction", Settings.TweetBoxClosingAction.Confirm);

        public static readonly SettingItemStruct<bool> IsBacktrackFallback =
            new SettingItemStruct<bool>("IsBacktrackFallback", true);

        public static readonly SettingItemStruct<bool> RestorePreviousStashed =
            new SettingItemStruct<bool>("RestorePreviousStashed", false);

        public static readonly SettingItemStruct<bool> ShowMessageOnTweetFailed =
            new SettingItemStruct<bool>("ShowMessageOnTweetFailed", true);

        #endregion

        #region Outer and Third Party services

        public static readonly SettingItem<string> ExternalBrowserPath =
            new SettingItem<string>("ExternalBrowserPath", null);

        public static readonly SettingItem<string> FavstarApiKey =
            new SettingItem<string>("FavstarApiKey", null);

        #endregion

        #region Notification and Confirmations

        public static readonly SettingItemStruct<bool> ConfirmOnExitApp =
            new SettingItemStruct<bool>("ConfirmOnExitApp", true);

        public static readonly SettingItemStruct<bool> PlaySounds =
            new SettingItemStruct<bool>("PlaySounds", true);

        public static readonly SettingItemStruct<NotificationUIType> NotificationType =
            new SettingItemStruct<NotificationUIType>("NotificationType", NotificationUIType.Slim);

        public static readonly SettingItemStruct<bool> NotifyWhenWindowIsActive =
            new SettingItemStruct<bool>("NotifyWhenWindowIsActive", false);

        public static readonly SettingItemStruct<bool> NotifyBackfilledTweets =
            new SettingItemStruct<bool>("NotifyBackfilledTweets", false);

        public static readonly SettingItemStruct<bool> NotifyMention =
            new SettingItemStruct<bool>("NotifyMention", true);

        public static readonly SettingItemStruct<bool> NotifyMessage =
            new SettingItemStruct<bool>("NotifyMessage", true);

        public static readonly SettingItemStruct<bool> NotifyFollow =
            new SettingItemStruct<bool>("NotifyFollow", true);

        public static readonly SettingItemStruct<bool> NotifyFavorite =
            new SettingItemStruct<bool>("NotifyFavorite", true);

        public static readonly SettingItemStruct<bool> NotifyRetweet =
            new SettingItemStruct<bool>("NotifyRetweet", true);

        public static readonly SettingItemStruct<int> NotifyScreenIndex =
            new SettingItemStruct<int>("NotifyScreenIndex", -1);

        #endregion

        #region High-level configurations

        public static readonly SettingItemStruct<bool> AcceptUnstableVersion =
            new SettingItemStruct<bool>("AcceptUnstableVersion", App.IsUnstableVersion);

        public static readonly SettingItemStruct<bool> UseInMemoryDatabase =
            new SettingItemStruct<bool>("UseInMemoryDatabase", false);

        public static readonly SettingItem<string> UserAgent =
            new SettingItem<string>("UserAgent", null);

        #region Web proxy configuration

        public static readonly SettingItemStruct<WebProxyConfiguration> WebProxyType =
            new SettingItemStruct<WebProxyConfiguration>("WebProxyType", WebProxyConfiguration.None);

        public static readonly SettingItem<string> WebProxyHost =
            new SettingItem<string>("WebProxyHost", String.Empty);

        public static readonly SettingItemStruct<int> WebProxyPort =
            new SettingItemStruct<int>("WebProxyPort", 0);

        public static readonly SettingItemStruct<bool> BypassWebProxyInLocal =
            new SettingItemStruct<bool>("BypassWebProxyInLocal", false);

        public static readonly SettingItem<string[]> WebProxyBypassList =
            new SettingItem<string[]>("WebProxyBypassList", null);

        #endregion

        public static readonly SettingItem<string> ApiProxy =
            new SettingItem<string>("ApiProxy", null);

        public static readonly SettingItem<string> SearchLocale =
            new SettingItem<string>("SearchLocale", null);

        public static readonly SettingItemStruct<bool> LoadPluginFromDevFolder =
            new SettingItemStruct<bool>("LoadPluginFromDevFolder", false);

        public static readonly SettingItemStruct<bool> DisableGeoLocationService =
            new SettingItemStruct<bool>("DisableGeoLocationService", false);

        public static readonly SettingItemStruct<int> EventDisplayMinimumMSec =
            new SettingItemStruct<int>("EventDisplayMinimumMSec", 200);

        public static readonly SettingItemStruct<int> EventDisplayMaximumMSec =
            new SettingItemStruct<int>("EventDisplayMaximumMSec", 3000);

        public static readonly SettingItemStruct<int> UserInfoReceivePeriod =
            new SettingItemStruct<int>("UserInfoReceivePeriod", 600);

        public static readonly SettingItemStruct<int> UserRelationReceivePeriod =
            new SettingItemStruct<int>("UserRelationReceivePeriod", 5400);

        public static readonly SettingItemStruct<int> RESTReceivePeriod =
            new SettingItemStruct<int>("RESTReceivePeriod", 90);

        public static readonly SettingItemStruct<int> RESTSearchReceivePeriod =
            new SettingItemStruct<int>("RESTSearchReceivePeriod", 90);

        public static readonly SettingItemStruct<int> ListReceivePeriod =
            new SettingItemStruct<int>("ListReceivePeriod", 90);

        public static readonly SettingItemStruct<int> ListMemberReceivePeriod =
            new SettingItemStruct<int>("ListMemberReceivePeriod", 1800);

        public static readonly SettingItemStruct<int> PostWindowTimeSec =
            new SettingItemStruct<int>("PostWindowTimeSec", 10800);

        public static readonly SettingItemStruct<int> PostLimitPerWindow =
            new SettingItemStruct<int>("PostLimitPerWindow", 128);

        public static readonly SettingItemStruct<bool> IsBehaviorLogEnabled =
            new SettingItemStruct<bool>("IsBehaviorLogEnabled", false);

        #endregion

        #region Krile internal state

        public static readonly SettingItemStruct<Rect> LastWindowPosition =
            new SettingItemStruct<Rect>("LastWindowPosition", Rect.Empty);

        public static readonly SettingItemStruct<WindowState> LastWindowState =
            new SettingItemStruct<WindowState>("LastWindowState", WindowState.Normal);

        public static readonly SettingItem<string> LastImageOpenDir =
            new SettingItem<string>("LastImageOpenDir", Environment.GetFolderPath(Environment.SpecialFolder.MyPictures));

        public static readonly SettingItemStruct<int> SettingVersion =
            new SettingItemStruct<int>("SettingVersion", 1);

        public static readonly SettingItemStruct<bool> ShowStartupConfigurationWarning =
            new SettingItemStruct<bool>("ShowStartupConfigurationWarning", true);

        public static readonly SettingItemStruct<bool> CheckDesktopHeap =
            new SettingItemStruct<bool>("CheckDesktopHeap", true);

        #endregion

        #region Setting infrastructure

        public class FilterSettingItem
        {
            private readonly bool _autoSave;
            private readonly string _name;
            private Func<TwitterStatus, bool> _evaluatorCache;

            private FilterExpressionRoot _expression;

            public FilterSettingItem(string name, bool autoSave = true)
            {
                _name = name;
                _autoSave = autoSave;
            }

            public string Name
            {
                get { return _name; }
            }

            public FilterExpressionRoot Value
            {
                get
                {
                    if (_expression != null) return _expression;

                    object value;
                    if (_settingValueHolder.TryGetValue(Name, out value))
                    {
                        try
                        {
                            return _expression = QueryCompiler.CompileFilters(value as string);
                        }
                        catch (FilterQueryException)
                        {
                        }
                    }
                    // return empty
                    return _expression = FilterExpressionRoot.GetEmpty(false);
                }
                set
                {
                    _expression = value;
                    _settingValueHolder[Name] = value.ToQuery();
                    _evaluatorCache = null;
                    if (_autoSave)
                    {
                        Save();
                    }
                    this.ValueChanged.SafeInvoke(value);
                }
            }

            public void AddPredicate(FilterExpressionBase expr)
            {
                var eq = expr.ToQuery();
                if (eq.StartsWith("where "))
                {
                    eq = eq.Substring(6);
                }
                AddPredicate(eq);
            }

            public void AddPredicate(string query)
            {
                Value = QueryCompiler.CompileFilters(Value.ToQuery() + " | " + query);
            }

            public Func<TwitterStatus, bool> Evaluator
            {
                get { return _evaluatorCache ?? (_evaluatorCache = Value.GetEvaluator()); }
            }

            public event Action<FilterExpressionBase> ValueChanged;
        }

        public abstract class SettingItemBase<T>
        {
            private readonly string _name;

            public SettingItemBase(string name)
            {
                this._name = name;
            }

            public string Name
            {
                get { return _name; }
            }

            public abstract T Value { get; set; }

            public event Action<T> ValueChanged;

            protected void RaiseValueChanged(T value)
            {
                ValueChanged.SafeInvoke(value);
            }

            public IDisposable ListenValueChanged(Action<T> listener)
            {
                return Observable.FromEvent<T>(
                    h => ValueChanged += h,
                    h => ValueChanged -= h)
                                 .Subscribe(listener);
            }
        }

        public class SettingItem<T> : SettingItemBase<T> where T : class
        {
            private readonly bool _autoSave;
            private readonly T _defaultValue;

            private T _valueCache;

            public SettingItem(string name, T defaultValue, bool autoSave = true)
                : base(name)
            {
                _defaultValue = defaultValue;
                _autoSave = autoSave;
            }

            public override T Value
            {
                get
                {
                    if (_valueCache != null) return _valueCache;

                    object value;
                    if (_settingValueHolder.TryGetValue(Name, out value))
                    {
                        return _valueCache = value as T;
                    }
                    return _valueCache = _defaultValue;
                }
                set
                {
                    _valueCache = value;
                    _settingValueHolder[Name] = value;
                    if (_autoSave)
                    {
                        Save();
                    }
                    RaiseValueChanged(value);
                }
            }
        }

        public class SettingItemStruct<T> : SettingItemBase<T> where T : struct
        {
            private readonly bool _autoSave;
            private readonly T _defaultValue;

            private T? _valueCache;

            public SettingItemStruct(string name, T defaultValue, bool autoSave = true)
                : base(name)
            {
                _defaultValue = defaultValue;
                _autoSave = autoSave;
            }

            public override T Value
            {
                get
                {
                    if (_valueCache != null) return _valueCache.Value;
                    object value;
                    return _settingValueHolder.TryGetValue(this.Name, out value)
                        ? (this._valueCache = (T)value).Value
                        : (this._valueCache = this._defaultValue).Value;
                }
                set
                {
                    _valueCache = value;
                    _settingValueHolder[Name] = value;
                    if (_autoSave)
                    {
                        Save();
                    }
                    RaiseValueChanged(value);
                }
            }
        }

        #endregion

        /// <summary>
        /// The flag identifies newbies of Krile.
        /// </summary>
        public static bool IsFirstGenerated { get; private set; }

        public static bool IsLoaded { get; private set; }

        private static string BackupFilePath
        {
            get { return App.ConfigurationFilePath + ".bak"; }
        }

        #region Load settings

        public static bool LoadSettings()
        {
            IsFirstGenerated = false;
            if (File.Exists(App.ConfigurationFilePath))
            {
                try
                {
                    LoadSettingsFromFile(App.ConfigurationFilePath);
                    return true;
                }
                catch (Exception ex)
                {
                    return RecoverySettings(ex);
                }
            }
            _settingValueHolder = new ConcurrentDictionary<string, object>();
            IsFirstGenerated = true;
            _manager = new AccountManager(_accounts);
            IsLoaded = true;
            return true;
        }

        private static void LoadSettingsFromFile(string xmlFile)
        {
            using (var fs = File.Open(xmlFile, FileMode.Open, FileAccess.Read))
            {
                _settingValueHolder = new ConcurrentDictionary<string, object>(
                    XamlServices.Load(fs) as IDictionary<string, object> ?? new Dictionary<string, object>());
            }
            _manager = new AccountManager(_accounts);
            IsLoaded = true;
        }

        private static bool RecoverySettings(Exception ex)
        {
            // check backup file is existed
            if (File.Exists(BackupFilePath))
            {
                // try reading backup file
                try
                {
                    LoadSettingsFromFile(BackupFilePath);
                    // overwrite corrupted file
                    Save(true);
                    return true;
                }
                catch (Exception)
                {
                }
            }

            // backup file is not existed or backup file is corrupted
            var option = new TaskDialogOptions
            {
                Title = SettingModelResources.LoadFailedTitle,
                MainIcon = VistaTaskDialogIcon.Error,
                MainInstruction = SettingModelResources.LoadFailedInst,
                Content = SettingModelResources.LoadFailedContent,
                ExpandedInfo = ex.ToString(),
                CommandButtons = new[]
                {
                    SettingModelResources.LoadFailedCommandInitialize,
                    SettingModelResources.LoadFailedCommandBackup,
                    SettingModelResources.LoadFailedExit
                }
            };
            var result = TaskDialog.Show(option);
            if (!result.CommandButtonResult.HasValue ||
                result.CommandButtonResult.Value == 2)
            {
                // shutdown
                return false;
            }
            if (result.CommandButtonResult == 1)
            {
                try
                {
                    var cpfn = "Krile_CorruptedConfig_" + Path.GetRandomFileName() + ".xml";
                    File.Copy(App.ConfigurationFilePath, Path.Combine(
                        Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory),
                        cpfn));
                }
                catch (Exception iex)
                {
                    var noption = new TaskDialogOptions
                    {
                        Title = SettingModelResources.BackupFailedTitle,
                        MainIcon = VistaTaskDialogIcon.Error,
                        MainInstruction = SettingModelResources.BackupFailedInst,
                        Content = SettingModelResources.BackupFailedContent,
                        ExpandedInfo = iex.ToString(),
                        CommandButtons = new[] { SettingModelResources.BackupFailedExit }
                    };
                    TaskDialog.Show(noption);
                    return false;
                }
            }
            File.Delete(App.ConfigurationFilePath);
            _settingValueHolder = new ConcurrentDictionary<string, object>();
            _manager = new AccountManager(_accounts);
            IsLoaded = true;
            return true;
        }

        #endregion

        #region Save settings

        public static void Save()
        {
            Save(false);
        }

        private static void Save(bool skipBackup)
        {
            // save before load cause loss the setting!
            if (!IsLoaded) return;
            lock (_settingValueHolder)
            {
                try
                {
                    // create temporary file
                    var tempfile = Path.Combine(App.ConfigurationDirectoryPath, Path.GetRandomFileName());
                    using (var fs = File.Open(tempfile, FileMode.Create, FileAccess.ReadWrite))
                    {
                        // sort by key
                        var sd = new SortedDictionary<string, object>(_settingValueHolder);
                        XamlServices.Save(fs, sd);
                    }
                    var backup = skipBackup ? null : BackupFilePath;

                    // File.Replace is too buggy to use.
                    // File.Replace(tempfile, App.ConfigurationFilePath, backup);
                    if (File.Exists(App.ConfigurationFilePath))
                    {
                        if (backup != null)
                        {
                            if (File.Exists(backup))
                            {
                                File.Delete(backup);
                            }
                            File.Move(App.ConfigurationFilePath, backup);
                        }
                        else
                        {
                            File.Delete(App.ConfigurationFilePath);
                        }
                    }
                    File.Move(tempfile, App.ConfigurationFilePath);
                }
                catch (IOException)
                {
                    // file error.
                }
                catch (UnauthorizedAccessException)
                {
                    // could not write.
                }
            }
        }

        #endregion
    }

    public enum TweetDisplayMode
    {
        SingleLine,
        MultiLine,
        MixedSingleLine,
        MixedMultiLine,
        Expanded
    }

    public enum ScrollLockStrategy
    {
        /// <summary>
        ///     Always unlock
        /// </summary>
        None,

        /// <summary>
        ///     Always scroll locked
        /// </summary>
        Always,

        /// <summary>
        ///     Change lock/unlock explicitly
        /// </summary>
        Explicit,

        /// <summary>
        ///     If scrolled (scroll offset != 0)
        /// </summary>
        WhenScrolled,

        /// <summary>
        ///     When mouse over
        /// </summary>
        WhenMouseOver,
    }

    public enum TweetBoxClosingAction
    {
        Confirm,
        SaveToDraft,
        Discard,
    }

    public enum WebProxyConfiguration
    {
        Default,
        None,
        Custom
    }

    public enum TimelineIconResolution
    {
        Original,
        High,
        Optimized,
        Low,
        None
    }

    public enum InputUserSuggestMode
    {
        All,
        RelatedOnly,
        FollowingsOnly,
    }

    public enum ThumbnailMode
    {
        None,
        Single,
        All
    }

}