//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarryEyes.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarryEyes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Krile StarryEyes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refer Microsoft KB に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgButtonBrowseMsKb {
            get {
                return ResourceManager.GetString("MsgButtonBrowseMsKb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgButtonCancel {
            get {
                return ResourceManager.GetString("MsgButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changing database path is a debug feature, you should not use this option as part of customize for daily use. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDatabasePathWarningContent {
            get {
                return ResourceManager.GetString("MsgDatabasePathWarningContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Krile may crash when you put a setting file or a database file on cloud storage (e.g. OneDrive, Dropbox). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDatabasePathWarningFooter {
            get {
                return ResourceManager.GetString("MsgDatabasePathWarningFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database path is specified explicitly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDatabasePathWarningInst {
            get {
                return ResourceManager.GetString("MsgDatabasePathWarningInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database path warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDatabasePathWarningTitle {
            get {
                return ResourceManager.GetString("MsgDatabasePathWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maybe designation of database path is invalid.
        ///Please examine krile.exe.config . に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDbPathInvalidContent {
            get {
                return ResourceManager.GetString("MsgDbPathInvalidContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It will cause crashing Krile or hanging up your system.
        ///Changing configuration of Windows may prevent this problem. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDesktopHeapContent {
            get {
                return ResourceManager.GetString("MsgDesktopHeapContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desktop Heap parameter is too small.
        ///Current value: {0} / Lowest recommend: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDesktopHeapInfo {
            get {
                return ResourceManager.GetString("MsgDesktopHeapInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   May fall into memory shortage. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDesktopHeapInst {
            get {
                return ResourceManager.GetString("MsgDesktopHeapInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Don&apos;t ask me again に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDoNotAskMeAgain {
            get {
                return ResourceManager.GetString("MsgDoNotAskMeAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execution mode is a debug feature, you should not use this option as part of customize for daily use. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgExecModeWarningContent {
            get {
                return ResourceManager.GetString("MsgExecModeWarningContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Krile may crash when you put a setting file or a database file on cloud storage (e.g. OneDrive, Dropbox). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgExecModeWarningFooter {
            get {
                return ResourceManager.GetString("MsgExecModeWarningFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execution Mode has set as Standalone. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgExecModeWarningInst {
            get {
                return ResourceManager.GetString("MsgExecModeWarningInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execution Mode Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgExecModeWarningTitle {
            get {
                return ResourceManager.GetString("MsgExecModeWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to exit Krile? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgExitInst {
            get {
                return ResourceManager.GetString("MsgExitInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit Krile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgExitTitle {
            get {
                return ResourceManager.GetString("MsgExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Don&apos;t ask me again before exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgExitVerification {
            get {
                return ResourceManager.GetString("MsgExitVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgInstructionTabWarning {
            get {
                return ResourceManager.GetString("MsgInstructionTabWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If problem is not solved, please re-installing Krile. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgReInstallKrile {
            get {
                return ResourceManager.GetString("MsgReInstallKrile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Starting krile has failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgStartupErrorInst {
            get {
                return ResourceManager.GetString("MsgStartupErrorInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Krile Startup Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgStartupErrorTitle {
            get {
                return ResourceManager.GetString("MsgStartupErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tab information is empty.
        ///Generate default tabs? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgTabWarningContent {
            get {
                return ResourceManager.GetString("MsgTabWarningContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tab information may have been lost. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgTabWarningInst {
            get {
                return ResourceManager.GetString("MsgTabWarningInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tab Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgTabWarningTitle {
            get {
                return ResourceManager.GetString("MsgTabWarningTitle", resourceCulture);
            }
        }
    }
}
