//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarryEyes.Globalization.Models {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SubsystemResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubsystemResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarryEyes.Globalization.Models.SubsystemResources", typeof(SubsystemResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Restart Krile and retry, or update by manual. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoUpdateFailedContent {
            get {
                return ResourceManager.GetString("AutoUpdateFailedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not start update. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoUpdateFailedInst {
            get {
                return ResourceManager.GetString("AutoUpdateFailedInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto update error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoUpdateFailedTitle {
            get {
                return ResourceManager.GetString("AutoUpdateFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed checking updates. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FailedCheckingUpdate {
            get {
                return ResourceManager.GetString("FailedCheckingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed preparing updates. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FailedPrepareUpdate {
            get {
                return ResourceManager.GetString("FailedPrepareUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed receiving twitter api configuration. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TwitterConfigurationReceiveError {
            get {
                return ResourceManager.GetString("TwitterConfigurationReceiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateAvailableButtonImmediate {
            get {
                return ResourceManager.GetString("UpdateAvailableButtonImmediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Later に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateAvailableButtonLater {
            get {
                return ResourceManager.GetString("UpdateAvailableButtonLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update will be completed in a minute. Update right now? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateAvailableContent {
            get {
                return ResourceManager.GetString("UpdateAvailableContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New version of Krile is available. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateAvailableInst {
            get {
                return ResourceManager.GetString("UpdateAvailableInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Krile Automatic Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateAvailableTitle {
            get {
                return ResourceManager.GetString("UpdateAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove update folder located in user data directory. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateCompleteErrorContent {
            get {
                return ResourceManager.GetString("UpdateCompleteErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please reference FAQ for find location.
        ///If you can&apos;t delete it, you may need restarting Windows. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateCompleteErrorExInfo {
            get {
                return ResourceManager.GetString("UpdateCompleteErrorExInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed removing update agent. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateCompleteErrorInst {
            get {
                return ResourceManager.GetString("UpdateCompleteErrorInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update completion error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateCompleteErrorTitle {
            get {
                return ResourceManager.GetString("UpdateCompleteErrorTitle", resourceCulture);
            }
        }
    }
}
