//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarryEyes.Globalization.Filters {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QueryCompletionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueryCompletionResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarryEyes.Globalization.Filters.QueryCompletionResources", typeof(QueryCompletionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   [Set] Following users に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AcccountObjectFollowings {
            get {
                return ResourceManager.GetString("AcccountObjectFollowings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Set] Blocking users に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountObjectBlockings {
            get {
                return ResourceManager.GetString("AccountObjectBlockings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Set] Followers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountObjectFollowers {
            get {
                return ResourceManager.GetString("AccountObjectFollowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify source query after keyword &quot;from&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeywordFrom {
            get {
                return ResourceManager.GetString("KeywordFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify filter query after keyword &quot;filter&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeywordWhere {
            get {
                return ResourceManager.GetString("KeywordWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Conversation timeline (argument: tweet id [required]) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SourceConv {
            get {
                return ResourceManager.GetString("SourceConv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User&apos;s home timeline (argument: user @id [optional]) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SourceHome {
            get {
                return ResourceManager.GetString("SourceHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List (argument: receiver @id/list owner @id/list name [required except receiver @id]) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SourceList {
            get {
                return ResourceManager.GetString("SourceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweets in Krile (argument: referencing tab name [optional]) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SourceLocal {
            get {
                return ResourceManager.GetString("SourceLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mention timeline (argument: user @id [optional]) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SourceMention {
            get {
                return ResourceManager.GetString("SourceMention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Direct message (argument: user @id [optional]) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SourceMessages {
            get {
                return ResourceManager.GetString("SourceMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search timeline (argument: search argument [required]) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SourceSearch {
            get {
                return ResourceManager.GetString("SourceSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stream timeline (argument: search argument [ASCII only, required]) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SourceTrack {
            get {
                return ResourceManager.GetString("SourceTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet of specified user (argument : user @id or numeric #id [required]) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SourceUser {
            get {
                return ResourceManager.GetString("SourceUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [String] Profile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserObjectBio {
            get {
                return ResourceManager.GetString("UserObjectBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Boolean] User is enabled contributors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserObjectContributorsEnabled {
            get {
                return ResourceManager.GetString("UserObjectContributorsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Numeric] Favorites count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserObjectFavorites {
            get {
                return ResourceManager.GetString("UserObjectFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Numeric] Followers count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserObjectFollowers {
            get {
                return ResourceManager.GetString("UserObjectFollowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Numeric] Followings count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserObjectFollowings {
            get {
                return ResourceManager.GetString("UserObjectFollowings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Boolean] User is enabled geolocation info に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserObjectGeoEnabled {
            get {
                return ResourceManager.GetString("UserObjectGeoEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Numeric] Id に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserObjectId {
            get {
                return ResourceManager.GetString("UserObjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [String] Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserObjectLanguage {
            get {
                return ResourceManager.GetString("UserObjectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Numeric] Listed count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserObjectListedCount {
            get {
                return ResourceManager.GetString("UserObjectListedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [String] Location に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserObjectLocation {
            get {
                return ResourceManager.GetString("UserObjectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [String] User name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserObjectName {
            get {
                return ResourceManager.GetString("UserObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Boolean] User is protected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserObjectProtected {
            get {
                return ResourceManager.GetString("UserObjectProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [String] Screen name (@id) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserObjectScreenName {
            get {
                return ResourceManager.GetString("UserObjectScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Numeric] Tweet count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserObjectStatuses {
            get {
                return ResourceManager.GetString("UserObjectStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Boolean] User is translator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserObjectTranslator {
            get {
                return ResourceManager.GetString("UserObjectTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Boolean] User is verified に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserObjectVerified {
            get {
                return ResourceManager.GetString("UserObjectVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [String] Body of text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VariableBody {
            get {
                return ResourceManager.GetString("VariableBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Boolean] This is direct messaage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VariableDirectMessage {
            get {
                return ResourceManager.GetString("VariableDirectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Num/Set] Favorited count/favorited user ids に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VariableFavorites {
            get {
                return ResourceManager.GetString("VariableFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Boolean]  Tweet has media に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VariableHasMedia {
            get {
                return ResourceManager.GetString("VariableHasMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Numeric] ID of tweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VariableId {
            get {
                return ResourceManager.GetString("VariableId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Numeric] ID of reply to status に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VariableInReplyTo {
            get {
                return ResourceManager.GetString("VariableInReplyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Set](list.user.slug) Registered user in list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VariableList {
            get {
                return ResourceManager.GetString("VariableList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Boolean] This is retweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VariableRetweet {
            get {
                return ResourceManager.GetString("VariableRetweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [User] Retweeter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VariableRetweeter {
            get {
                return ResourceManager.GetString("VariableRetweeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Num/Set] Retweeted count/retweeted user ids に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VariableRetweets {
            get {
                return ResourceManager.GetString("VariableRetweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Num/Str/Set] User in reply to id/name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VariableTo {
            get {
                return ResourceManager.GetString("VariableTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Account] Registered accounts in Krile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VariableUs {
            get {
                return ResourceManager.GetString("VariableUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [User] User of tweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VariableUser {
            get {
                return ResourceManager.GetString("VariableUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [String] User&apos;s client name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VariableVia {
            get {
                return ResourceManager.GetString("VariableVia", resourceCulture);
            }
        }
    }
}
