//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarryEyes.Globalization.Filters {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QueryCompilerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueryCompilerResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarryEyes.Globalization.Filters.QueryCompilerResources", typeof(QueryCompilerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Query: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterQueryExceptionQuery {
            get {
                return ResourceManager.GetString("FilterQueryExceptionQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filter {0} could not convert type {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterQueryExceptionUnsupportedTypeFormat {
            get {
                return ResourceManager.GetString("FilterQueryExceptionUnsupportedTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filter {0} could not convert any type of {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterQueryExceptionUnsupportedTypeManyFormat {
            get {
                return ResourceManager.GetString("FilterQueryExceptionUnsupportedTypeManyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Query is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueryCompileFailed {
            get {
                return ResourceManager.GetString("QueryCompileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Query ends with backslash. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueryEndsWithBackslash {
            get {
                return ResourceManager.GetString("QueryEndsWithBackslash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Query is interrupted on halfway. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueryInterrupted {
            get {
                return ResourceManager.GetString("QueryInterrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid token: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueryInvalidToken {
            get {
                return ResourceManager.GetString("QueryInvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   query must be started with keyword &quot;from&quot; or &quot;where&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueryMustBeStartedWithFromOrWhere {
            get {
                return ResourceManager.GetString("QueryMustBeStartedWithFromOrWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This token is predicted as next: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueryPredictNextToken {
            get {
                return ResourceManager.GetString("QueryPredictNextToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   String is not closed: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueryStringIsNotClosed {
            get {
                return ResourceManager.GetString("QueryStringIsNotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown source: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueryUnknownFilterSource {
            get {
                return ResourceManager.GetString("QueryUnknownFilterSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close Parenthesis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenCloseParenthesis {
            get {
                return ResourceManager.GetString("TokenCloseParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close Bracket に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenCloseSquareBracket {
            get {
                return ResourceManager.GetString("TokenCloseSquareBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Collon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenCollon {
            get {
                return ResourceManager.GetString("TokenCollon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comma に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenComma {
            get {
                return ResourceManager.GetString("TokenComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exclamation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenExclamation {
            get {
                return ResourceManager.GetString("TokenExclamation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Literal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenLiteral {
            get {
                return ResourceManager.GetString("TokenLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Parenthesis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenOpenParenthesis {
            get {
                return ResourceManager.GetString("TokenOpenParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Bracket に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenOpenSquareBracket {
            get {
                return ResourceManager.GetString("TokenOpenSquareBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logical And に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenOperatorAnd {
            get {
                return ResourceManager.GetString("TokenOperatorAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contains に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenOperatorContains {
            get {
                return ResourceManager.GetString("TokenOperatorContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Divide に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenOperatorDivide {
            get {
                return ResourceManager.GetString("TokenOperatorDivide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenOperatorEquals {
            get {
                return ResourceManager.GetString("TokenOperatorEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Greater Than に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenOperatorGreaterThan {
            get {
                return ResourceManager.GetString("TokenOperatorGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Greater Than or Equal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenOperatorGreaterThanOrEqual {
            get {
                return ResourceManager.GetString("TokenOperatorGreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenOperatorIn {
            get {
                return ResourceManager.GetString("TokenOperatorIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Less Than に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenOperatorLessThan {
            get {
                return ResourceManager.GetString("TokenOperatorLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Less Than or Equal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenOperatorLessThanOrEqual {
            get {
                return ResourceManager.GetString("TokenOperatorLessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minus に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenOperatorMinus {
            get {
                return ResourceManager.GetString("TokenOperatorMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multiple に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenOperatorMultiple {
            get {
                return ResourceManager.GetString("TokenOperatorMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Equal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenOperatorNotEquals {
            get {
                return ResourceManager.GetString("TokenOperatorNotEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logical Or に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenOperatorOr {
            get {
                return ResourceManager.GetString("TokenOperatorOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plus に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenOperatorPlus {
            get {
                return ResourceManager.GetString("TokenOperatorPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Period に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenPeriod {
            get {
                return ResourceManager.GetString("TokenPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   String に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenString {
            get {
                return ResourceManager.GetString("TokenString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown token に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenUnknown {
            get {
                return ResourceManager.GetString("TokenUnknown", resourceCulture);
            }
        }
    }
}
