//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Detective.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Detective.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   SQLite database is corrupted.
        ///Restart krile to rebuild database.
        ///
        ///If rebuild is not suggested after restarting, please enter maintenance mode manually or delete database via explorer.
        ///Refer official web site for how to enter mantenance mode or finding location of database files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DatabaseImageIsMalformed {
            get {
                return ResourceManager.GetString("DatabaseImageIsMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SQLite file is locked by other processes.
        ///Could not access to krile.db, krile.db-wal, krile.db-shm.
        ///
        ///This probrem was occured by below reason:
        ///* Synchronizing file by Cloud Storage Deamons
        ///* Scanning file by Anti-Virus Softwares
        ///* Sharing file on Network Drive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DatabaseIsLocked {
            get {
                return ResourceManager.GetString("DatabaseIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Essential library is missing or load failed.
        ///Suggested reason is below:
        ///
        ///* File is not correctly located
        ///  When automatic update is failed, sometimes files are not located or update, or broken.
        ///  Please re-installing Krile.
        ///
        ///* Execute Krile on unsupported platform
        ///  Windows Vista or later is supported.
        ///  Ensure not running on virtual machines or emulators.
        ///
        ///* Authority is required
        ///  Please start krile with administrator authority.
        ///
        ///* .NET Framework is corrupted
        ///  Please re-install .NET Framew [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EssentialFileIsMissing {
            get {
                return ResourceManager.GetString("EssentialFileIsMissing", resourceCulture);
            }
        }
    }
}
