//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarryEyes.Globalization.Dialogs {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AddNewKeyAssignWindowResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddNewKeyAssignWindowResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarryEyes.Globalization.Dialogs.AddNewKeyAssignWindowResources", typeof(AddNewKeyAssignWindowResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add key assign に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddKeyAssignTitle {
            get {
                return ResourceManager.GetString("AddKeyAssignTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create _empty file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateEmpty {
            get {
                return ResourceManager.GetString("CreateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create new key assign file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateNewKeyAssignFile {
            get {
                return ResourceManager.GetString("CreateNewKeyAssignFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create _copy with current file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateWithCopy {
            get {
                return ResourceManager.GetString("CreateWithCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用できない文字が含まれています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorFileNameContainsInvalidChars {
            get {
                return ResourceManager.GetString("ErrorFileNameContainsInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同じ名前のキーアサインがすでに存在します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorFileNameIsDuplicated {
            get {
                return ResourceManager.GetString("ErrorFileNameIsDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル名が入力されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorFileNameIsEmpty {
            get {
                return ResourceManager.GetString("ErrorFileNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key Assign Name:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyAssignName {
            get {
                return ResourceManager.GetString("KeyAssignName", resourceCulture);
            }
        }
    }
}
