//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarryEyes.Globalization.Dialogs {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class KeyOverrideWindowResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeyOverrideWindowResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarryEyes.Globalization.Dialogs.KeyOverrideWindowResources", typeof(KeyOverrideWindowResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Register API key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HeaderText {
            get {
                return ResourceManager.GetString("HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   How to get API key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HelpLink {
            get {
                return ResourceManager.GetString("HelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register your API key for using Krile with more comfortableness. You can skip this step but some functions will be restricted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InstructionText {
            get {
                return ResourceManager.GetString("InstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please check inputted data and try again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgAuthErrorContent {
            get {
                return ResourceManager.GetString("MsgAuthErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can watch this message when twitter is disrupting services or clock of your computer loses time. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgAuthErrorFooter {
            get {
                return ResourceManager.GetString("MsgAuthErrorFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not verify your API key. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgAuthErrorInst {
            get {
                return ResourceManager.GetString("MsgAuthErrorInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OAuth Authorization Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgAuthErrorTitle {
            get {
                return ResourceManager.GetString("MsgAuthErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please use other keys. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgBlockingKeyContent {
            get {
                return ResourceManager.GetString("MsgBlockingKeyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You cannot use this key. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgBlockingKeyInst {
            get {
                return ResourceManager.GetString("MsgBlockingKeyInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inputted data contains illegal characters.
        ///Please examine inputted consumer key. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgInvalidKeyContent {
            get {
                return ResourceManager.GetString("MsgInvalidKeyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consumer key is wrong. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgInvalidKeyInst {
            get {
                return ResourceManager.GetString("MsgInvalidKeyInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inputted data contains illegal characters.
        ///Please examine inputted consumer secret. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgInvalidSecretContent {
            get {
                return ResourceManager.GetString("MsgInvalidSecretContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consumer secret is wrong. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgInvalidSecretInst {
            get {
                return ResourceManager.GetString("MsgInvalidSecretInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key Setting Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgKeySettingError {
            get {
                return ResourceManager.GetString("MsgKeySettingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only two accounts are allowed to register to Krile if you skip setting keys. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgSkipContent {
            get {
                return ResourceManager.GetString("MsgSkipContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your account may be unable to register depending on the situation of the API key.
        ///You can set API key after this, but you need remove all accounts from Krile before setting API keys. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgSkipExInfo {
            get {
                return ResourceManager.GetString("MsgSkipExInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to skip setting API Key? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgSkipInst {
            get {
                return ResourceManager.GetString("MsgSkipInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skipping API Key setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgSkipTitle {
            get {
                return ResourceManager.GetString("MsgSkipTitle", resourceCulture);
            }
        }
    }
}
