//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarryEyes.Globalization.WindowParts {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralFlipResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralFlipResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarryEyes.Globalization.WindowParts.GeneralFlipResources", typeof(GeneralFlipResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Click to toggle selection this account.
        ///Right click to select this account only. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountSelectionHelp {
            get {
                return ResourceManager.GetString("AccountSelectionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tab name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabConfigNameHelp {
            get {
                return ResourceManager.GetString("TabConfigNameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification sound of this tab に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabConfigNotificationSound {
            get {
                return ResourceManager.GetString("TabConfigNotificationSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wave file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabConfigOpenSoundFilter {
            get {
                return ResourceManager.GetString("TabConfigOpenSoundFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select notification sound に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabConfigOpenSoundTitle {
            get {
                return ResourceManager.GetString("TabConfigOpenSoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Query of this tab に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabConfigQuery {
            get {
                return ResourceManager.GetString("TabConfigQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Query contains some errors. This result will not saved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabConfigQueryContainsError {
            get {
                return ResourceManager.GetString("TabConfigQueryContainsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Krile Query Help... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabConfigQueryHelp {
            get {
                return ResourceManager.GetString("TabConfigQueryHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Query is compiled successfully. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabConfigQueryValid {
            get {
                return ResourceManager.GetString("TabConfigQueryValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show new tweet count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabConfigShowCounts {
            get {
                return ResourceManager.GetString("TabConfigShowCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Popup new tweets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabConfigShowPopup {
            get {
                return ResourceManager.GetString("TabConfigShowPopup", resourceCulture);
            }
        }
    }
}
