//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarryEyes.Globalization.WindowParts {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InputAreaResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputAreaResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarryEyes.Globalization.WindowParts.InputAreaResources", typeof(InputAreaResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Account is automatically selected. Click to unlock に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountIsAutomaticallySelected {
            get {
                return ResourceManager.GetString("AccountIsAutomaticallySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Account selected. Click on the left area to select an account to post tweets. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountIsNotSelected {
            get {
                return ResourceManager.GetString("AccountIsNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Account selected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountSelectorNotSelected {
            get {
                return ResourceManager.GetString("AccountSelectorNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   selected: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountSelectorSelectedFormat {
            get {
                return ResourceManager.GetString("AccountSelectorSelectedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amending last posted tweet. Close post box for cancel amending に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AmendingPreviousOne {
            get {
                return ResourceManager.GetString("AmendingPreviousOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amend last posted tweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AmendPreviousOne {
            get {
                return ResourceManager.GetString("AmendPreviousOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   attach from clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AttachClipboardImage {
            get {
                return ResourceManager.GetString("AttachClipboardImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AttachImageDlgFilterAll {
            get {
                return ResourceManager.GetString("AttachImageDlgFilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Images に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AttachImageDlgFilterImg {
            get {
                return ResourceManager.GetString("AttachImageDlgFilterImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify attaching image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AttachImageDlgTitle {
            get {
                return ResourceManager.GetString("AttachImageDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   attach or update location に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AttachOrUpdateLocation {
            get {
                return ResourceManager.GetString("AttachOrUpdateLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click to cancel attaching に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClickToRemoveImage {
            get {
                return ResourceManager.GetString("ClickToRemoveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click to select posting account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClickToSelectAccount {
            get {
                return ResourceManager.GetString("ClickToSelectAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   delete location に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteLocation {
            get {
                return ResourceManager.GetString("DeleteLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} drafts saved に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DraftCountFormat {
            get {
                return ResourceManager.GetString("DraftCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drafts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Drafts {
            get {
                return ResourceManager.GetString("Drafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options for attaching image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageAttachOption {
            get {
                return ResourceManager.GetString("ImageAttachOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lockable hashtags に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LockableHashtags {
            get {
                return ResourceManager.GetString("LockableHashtags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Locked hashtags に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LockedHashtags {
            get {
                return ResourceManager.GetString("LockedHashtags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet will be posted even if deleting last status is failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgAmendContent {
            get {
                return ResourceManager.GetString("MsgAmendContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleting tweet:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgAmendExInfo {
            get {
                return ResourceManager.GetString("MsgAmendExInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ({0} tweets will be deleted) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgAmendExInfoMultipleFormat {
            get {
                return ResourceManager.GetString("MsgAmendExInfoMultipleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete last tweet and repost this. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgAmendInst {
            get {
                return ResourceManager.GetString("MsgAmendInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amending tweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgAmendTitle {
            get {
                return ResourceManager.GetString("MsgAmendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error has occurred while loading image.
        ///Image might be incompatible or corrupted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgImageLoadErrorContent {
            get {
                return ResourceManager.GetString("MsgImageLoadErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not attach the image. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgImageLoadErrorInst {
            get {
                return ResourceManager.GetString("MsgImageLoadErrorInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image load error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgImageLoadErrorTitle {
            get {
                return ResourceManager.GetString("MsgImageLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save current content to drafts? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgSaveToDraftInst {
            get {
                return ResourceManager.GetString("MsgSaveToDraftInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save to drafts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgSaveToDraftTitle {
            get {
                return ResourceManager.GetString("MsgSaveToDraftTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Try to start Snipping Tool via start screen. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgSnippingToolErrorContent {
            get {
                return ResourceManager.GetString("MsgSnippingToolErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not start Snipping Tool. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgSnippingToolErrorInst {
            get {
                return ResourceManager.GetString("MsgSnippingToolErrorInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Snipping Tool error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgSnippingToolErrorTitle {
            get {
                return ResourceManager.GetString("MsgSnippingToolErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are going to continue conversation with ANOTHER ACCOUNT.
        ///Are you sure you want to continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgThirdReplyWarnContent {
            get {
                return ResourceManager.GetString("MsgThirdReplyWarnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reply with Wrong Account - Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgThirdReplyWarnTitle {
            get {
                return ResourceManager.GetString("MsgThirdReplyWarnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: {0}
        ///Do you want to retry? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgTweetFailedContentFormat {
            get {
                return ResourceManager.GetString("MsgTweetFailedContentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you do not want to retry, body of tweet will be saved to draft. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgTweetFailedFooter {
            get {
                return ResourceManager.GetString("MsgTweetFailedFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet has failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgTweetFailedInst {
            get {
                return ResourceManager.GetString("MsgTweetFailedInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet is a duplicate. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgTweetFailedReasonDuplicate {
            get {
                return ResourceManager.GetString("MsgTweetFailedReasonDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   POST limited. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgTweetFailedReasonPostLimited {
            get {
                return ResourceManager.GetString("MsgTweetFailedReasonPostLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Analysis failed or unknown error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgTweetFailedReasonUnknown {
            get {
                return ResourceManager.GetString("MsgTweetFailedReasonUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgTweetFailedTitle {
            get {
                return ResourceManager.GetString("MsgTweetFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Post tweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PostTweet {
            get {
                return ResourceManager.GetString("PostTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} tweets remain until post-limit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemainUpdateFormat {
            get {
                return ResourceManager.GetString("RemainUpdateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   select image file to attach... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectAttachImageFile {
            get {
                return ResourceManager.GetString("SelectAttachImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   snipping tool... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartSnippingTool {
            get {
                return ResourceManager.GetString("StartSnippingTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading attached image... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusImageLoading {
            get {
                return ResourceManager.GetString("StatusImageLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle URL auto-link avoidance に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToggleUrlAutoEscape {
            get {
                return ResourceManager.GetString("ToggleUrlAutoEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL auto-link avoidance is disabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UrlAutoEscapeDisabled {
            get {
                return ResourceManager.GetString("UrlAutoEscapeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL auto-link avoidance is enabled (Insert zero-width space before TLD of URL without schemes.) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UrlAutoEscapeEnabled {
            get {
                return ResourceManager.GetString("UrlAutoEscapeEnabled", resourceCulture);
            }
        }
    }
}
