//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarryEyes.Globalization.WindowParts {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainAreaTimelineResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainAreaTimelineResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarryEyes.Globalization.WindowParts.MainAreaTimelineResources", typeof(MainAreaTimelineResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Copy failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgClipboardErrorInst {
            get {
                return ResourceManager.GetString("MsgClipboardErrorInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clipboard error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgClipboardErrorTitle {
            get {
                return ResourceManager.GetString("MsgClipboardErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDeleteCmdDelete {
            get {
                return ResourceManager.GetString("MsgDeleteCmdDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleted tweet can not be restored. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDeleteContent {
            get {
                return ResourceManager.GetString("MsgDeleteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amend last one tweet is available on post box. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDeleteFooter {
            get {
                return ResourceManager.GetString("MsgDeleteFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amend last one tweet is available on post box with {0} key. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDeleteFooterWithKeyFormat {
            get {
                return ResourceManager.GetString("MsgDeleteFooterWithKeyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete tweet? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDeleteInst {
            get {
                return ResourceManager.GetString("MsgDeleteInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete tweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDeleteTitle {
            get {
                return ResourceManager.GetString("MsgDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Favorite failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgFavoriteFailed {
            get {
                return ResourceManager.GetString("MsgFavoriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet could not be favorited. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgFavoriteFailedInst {
            get {
                return ResourceManager.GetString("MsgFavoriteFailedInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All tweets from this client are remove from all tabs. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgMuteClientContent {
            get {
                return ResourceManager.GetString("MsgMuteClientContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to mute client {0} ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgMuteClientInstFormat {
            get {
                return ResourceManager.GetString("MsgMuteClientInstFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mute client に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgMuteClientTitle {
            get {
                return ResourceManager.GetString("MsgMuteClientTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgMuteCmdMute {
            get {
                return ResourceManager.GetString("MsgMuteCmdMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configure mute predicates is available in setting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgMuteFooter {
            get {
                return ResourceManager.GetString("MsgMuteFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All tweets that contains keyword are removed from all tabs. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgMuteKeywordContent {
            get {
                return ResourceManager.GetString("MsgMuteKeywordContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to mute keyword {0} ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgMuteKeywordInstFormat {
            get {
                return ResourceManager.GetString("MsgMuteKeywordInstFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click and drag text to select keywords. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgMuteKeywordSelectContent {
            get {
                return ResourceManager.GetString("MsgMuteKeywordSelectContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select keyword for muting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgMuteKeywordSelectInst {
            get {
                return ResourceManager.GetString("MsgMuteKeywordSelectInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mute keyword に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgMuteKeywordTitle {
            get {
                return ResourceManager.GetString("MsgMuteKeywordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All tweets from this user are removed from all tabs. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgMuteUserContent {
            get {
                return ResourceManager.GetString("MsgMuteUserContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to mute user {0} ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgMuteUserInstFormat {
            get {
                return ResourceManager.GetString("MsgMuteUserInstFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mute user に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgMuteUserTitle {
            get {
                return ResourceManager.GetString("MsgMuteUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Favorite is not allowed for this tweet. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgProhibitFavorite {
            get {
                return ResourceManager.GetString("MsgProhibitFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can&apos;t favorite direct messages! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgProhibitFavoriteDirectMessage {
            get {
                return ResourceManager.GetString("MsgProhibitFavoriteDirectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Favorite tweet posted by yourself is not allowed by setting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgProhibitFavoriteMyself {
            get {
                return ResourceManager.GetString("MsgProhibitFavoriteMyself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retweet is not allowed for this tweet. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgProhibitRetweet {
            get {
                return ResourceManager.GetString("MsgProhibitRetweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retweeting direct messages or protected user&apos;s tweet is not allowed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgProhibitRetweetDirectMessage {
            get {
                return ResourceManager.GetString("MsgProhibitRetweetDirectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can&apos;t retweet your own tweets! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgProhibitRetweetMyself {
            get {
                return ResourceManager.GetString("MsgProhibitRetweetMyself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Account is not selected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgQuickActionAccountIsNotSelected {
            get {
                return ResourceManager.GetString("MsgQuickActionAccountIsNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accounts must be selected for using quick actions.
        ///Selected accounts are memorized for each tabs. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgQuickActionAccountIsNotSelectedDetail {
            get {
                return ResourceManager.GetString("MsgQuickActionAccountIsNotSelectedDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   QuickAction error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgQuickActionFailedTitle {
            get {
                return ResourceManager.GetString("MsgQuickActionFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Report に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgReportAsSpamCmdReportAsSpam {
            get {
                return ResourceManager.GetString("MsgReportAsSpamCmdReportAsSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Block from all accounts, and report spam from one account. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgReportAsSpamContent {
            get {
                return ResourceManager.GetString("MsgReportAsSpamContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Report {0} as spam? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgReportAsSpamInstFormat {
            get {
                return ResourceManager.GetString("MsgReportAsSpamInstFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Report user as spam に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgReportAsSpamTitle {
            get {
                return ResourceManager.GetString("MsgReportAsSpamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retweet failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgRetweetFailed {
            get {
                return ResourceManager.GetString("MsgRetweetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet could not be deleted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgTweetDeleteFailed {
            get {
                return ResourceManager.GetString("MsgTweetDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unfavorite failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgUnfavoriteFailed {
            get {
                return ResourceManager.GetString("MsgUnfavoriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unretweet failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgUnretweetFailed {
            get {
                return ResourceManager.GetString("MsgUnretweetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Close this tab に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabClose {
            get {
                return ResourceManager.GetString("TabClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Clone tab に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabCreateCopy {
            get {
                return ResourceManager.GetString("TabCreateCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create _new tab... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabCreateNew {
            get {
                return ResourceManager.GetString("TabCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Edit... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabEdit {
            get {
                return ResourceManager.GetString("TabEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Restore last closed tab に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabRestoreLast {
            get {
                return ResourceManager.GetString("TabRestoreLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Notify new tweets in this tab に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabToggleNotify {
            get {
                return ResourceManager.GetString("TabToggleNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Copy to clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextCopyClipboard {
            get {
                return ResourceManager.GetString("TextCopyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy to _input box に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextCopyInput {
            get {
                return ResourceManager.GetString("TextCopyInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Mute keyword に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextMute {
            get {
                return ResourceManager.GetString("TextMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search _google... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextSearchGoogle {
            get {
                return ResourceManager.GetString("TextSearchGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Search in Krile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextSearchLocal {
            get {
                return ResourceManager.GetString("TextSearchLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search _twitter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextSearchTwitter {
            get {
                return ResourceManager.GetString("TextSearchTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineCmdDelete {
            get {
                return ResourceManager.GetString("TimelineCmdDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineCmdExtractAll {
            get {
                return ResourceManager.GetString("TimelineCmdExtractAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Favorite に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineCmdFavorite {
            get {
                return ResourceManager.GetString("TimelineCmdFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Favorite all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineCmdFavoriteAll {
            get {
                return ResourceManager.GetString("TimelineCmdFavoriteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Favorite and Retweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineCmdFavoriteAndRetweet {
            get {
                return ResourceManager.GetString("TimelineCmdFavoriteAndRetweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Favorite with selected account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineCmdFavoriteSelect {
            get {
                return ResourceManager.GetString("TimelineCmdFavoriteSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reply に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineCmdReply {
            get {
                return ResourceManager.GetString("TimelineCmdReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mention selected users に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineCmdReplyAll {
            get {
                return ResourceManager.GetString("TimelineCmdReplyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineCmdRetweet {
            get {
                return ResourceManager.GetString("TimelineCmdRetweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retweet with selected account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineCmdRetweetSelect {
            get {
                return ResourceManager.GetString("TimelineCmdRetweetSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unfavorite に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineCmdUnfavorite {
            get {
                return ResourceManager.GetString("TimelineCmdUnfavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unretweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineCmdUnretweet {
            get {
                return ResourceManager.GetString("TimelineCmdUnretweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unselect all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineCmdUnselectAll {
            get {
                return ResourceManager.GetString("TimelineCmdUnselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineDelete {
            get {
                return ResourceManager.GetString("TimelineDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not receive in reply to tweet. Click here to extract mention tree. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineErrorCouldNotReceiveInReplyTo {
            get {
                return ResourceManager.GetString("TimelineErrorCouldNotReceiveInReplyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Favorite に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineFavorite {
            get {
                return ResourceManager.GetString("TimelineFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F_avorite with selecting account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineFavoriteSelect {
            get {
                return ResourceManager.GetString("TimelineFavoriteSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Mute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineMute {
            get {
                return ResourceManager.GetString("TimelineMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Mute client に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineMuteClient {
            get {
                return ResourceManager.GetString("TimelineMuteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mute _user に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineMuteUser {
            get {
                return ResourceManager.GetString("TimelineMuteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Quote に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineQuote {
            get {
                return ResourceManager.GetString("TimelineQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Quote permalink に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineQuotePermalink {
            get {
                return ResourceManager.GetString("TimelineQuotePermalink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Unofficial Retweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineQuoteUnofficialRetweet {
            get {
                return ResourceManager.GetString("TimelineQuoteUnofficialRetweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receive _older tweets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineReceiveOlder {
            get {
                return ResourceManager.GetString("TimelineReceiveOlder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reply(_M) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineReply {
            get {
                return ResourceManager.GetString("TimelineReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reply All(_M) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineReplyAll {
            get {
                return ResourceManager.GetString("TimelineReplyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Retweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineRetweet {
            get {
                return ResourceManager.GetString("TimelineRetweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   R_etweet with selecting account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineRetweetSelect {
            get {
                return ResourceManager.GetString("TimelineRetweetSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Select に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineSelect {
            get {
                return ResourceManager.GetString("TimelineSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Extract users に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineSelectedExtract {
            get {
                return ResourceManager.GetString("TimelineSelectedExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Favorite all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineSelectedFavorite {
            get {
                return ResourceManager.GetString("TimelineSelectedFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Se_lected statuses に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineSelectedOperation {
            get {
                return ResourceManager.GetString("TimelineSelectedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Mention selected users に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineSelectedReplyAll {
            get {
                return ResourceManager.GetString("TimelineSelectedReplyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Unselect all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineSelectedUnselectAll {
            get {
                return ResourceManager.GetString("TimelineSelectedUnselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This _tweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineThisTweet {
            get {
                return ResourceManager.GetString("TimelineThisTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Copy body に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineThisTweetCopyBody {
            get {
                return ResourceManager.GetString("TimelineThisTweetCopyBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy _permalink に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineThisTweetCopyPermalink {
            get {
                return ResourceManager.GetString("TimelineThisTweetCopyPermalink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy _STOT に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineThisTweetCopySTOT {
            get {
                return ResourceManager.GetString("TimelineThisTweetCopySTOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Open conversation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineThisTweetOpenConversation {
            get {
                return ResourceManager.GetString("TimelineThisTweetOpenConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open _favstar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineThisTweetOpenFavstar {
            get {
                return ResourceManager.GetString("TimelineThisTweetOpenFavstar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open _web に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineThisTweetOpenWeb {
            get {
                return ResourceManager.GetString("TimelineThisTweetOpenWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This _user に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineThisUser {
            get {
                return ResourceManager.GetString("TimelineThisUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Direct message に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineThisUserDirectMessage {
            get {
                return ResourceManager.GetString("TimelineThisUserDirectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open _favstar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineThisUserOpenFavstar {
            get {
                return ResourceManager.GetString("TimelineThisUserOpenFavstar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open _twilog に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineThisUserOpenTwilog {
            get {
                return ResourceManager.GetString("TimelineThisUserOpenTwilog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Open twitter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineThisUserOpenTwitter {
            get {
                return ResourceManager.GetString("TimelineThisUserOpenTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Show profile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineThisUserProfile {
            get {
                return ResourceManager.GetString("TimelineThisUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Report as spam に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineThisUserReportSpam {
            get {
                return ResourceManager.GetString("TimelineThisUserReportSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Un_select に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineUnselect {
            get {
                return ResourceManager.GetString("TimelineUnselect", resourceCulture);
            }
        }
    }
}
