//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarryEyes.Globalization.WindowParts {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SearchFlipResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SearchFlipResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarryEyes.Globalization.WindowParts.SearchFlipResources", typeof(SearchFlipResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Could not delete saved queries. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InfoDeleteQueryFailed {
            get {
                return ResourceManager.GetString("InfoDeleteQueryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not receive saved queries(@{0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InfoSavedQueriesReceiveFailedFormat {
            get {
                return ResourceManager.GetString("InfoSavedQueriesReceiveFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Block failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgErrorBlockInst {
            get {
                return ResourceManager.GetString("MsgErrorBlockInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Block error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgErrorBlockTitle {
            get {
                return ResourceManager.GetString("MsgErrorBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Follow failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgErrorFollowInst {
            get {
                return ResourceManager.GetString("MsgErrorFollowInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Follow error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgErrorFollowTitle {
            get {
                return ResourceManager.GetString("MsgErrorFollowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mute failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgErrorMuteInst {
            get {
                return ResourceManager.GetString("MsgErrorMuteInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mute error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgErrorMuteTitle {
            get {
                return ResourceManager.GetString("MsgErrorMuteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spam report failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgErrorReportSpamInst {
            get {
                return ResourceManager.GetString("MsgErrorReportSpamInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spam report error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgErrorReportSpamTitle {
            get {
                return ResourceManager.GetString("MsgErrorReportSpamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Suppressing retweets failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgErrorSuppressRetweetsInst {
            get {
                return ResourceManager.GetString("MsgErrorSuppressRetweetsInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Supressing retweets error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgErrorSuppressRetweetsTitle {
            get {
                return ResourceManager.GetString("MsgErrorSuppressRetweetsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unblock failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgErrorUnblockInst {
            get {
                return ResourceManager.GetString("MsgErrorUnblockInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unblock error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgErrorUnblockTitle {
            get {
                return ResourceManager.GetString("MsgErrorUnblockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unfollow failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgErrorUnfollowInst {
            get {
                return ResourceManager.GetString("MsgErrorUnfollowInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unfollow error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgErrorUnfollowTitle {
            get {
                return ResourceManager.GetString("MsgErrorUnfollowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unmute failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgErrorUnmuteInst {
            get {
                return ResourceManager.GetString("MsgErrorUnmuteInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unmute error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgErrorUnmuteTitle {
            get {
                return ResourceManager.GetString("MsgErrorUnmuteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unsuppressing retweets failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgErrorUnsuppressRetweetsInst {
            get {
                return ResourceManager.GetString("MsgErrorUnsuppressRetweetsInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unsuppressing retweets error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgErrorUnsuppressRetweetsTitle {
            get {
                return ResourceManager.GetString("MsgErrorUnsuppressRetweetsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Followers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgUserFollowers {
            get {
                return ResourceManager.GetString("MsgUserFollowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Following に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgUserFollowing {
            get {
                return ResourceManager.GetString("MsgUserFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Account is not registered. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgUserInfoLoadErrorAccountIsNotExist {
            get {
                return ResourceManager.GetString("MsgUserInfoLoadErrorAccountIsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not load user information: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgUserInfoLoadErrorInstFormat {
            get {
                return ResourceManager.GetString("MsgUserInfoLoadErrorInstFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgUserInfoLoadErrorTitle {
            get {
                return ResourceManager.GetString("MsgUserInfoLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgUserProfile {
            get {
                return ResourceManager.GetString("MsgUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Delete this item に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchFlipDeleteSavedKeyword {
            get {
                return ResourceManager.GetString("SearchFlipDeleteSavedKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compiling... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchFlipQueryCompiling {
            get {
                return ResourceManager.GetString("SearchFlipQueryCompiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Query is empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchFlipQueryEmpty {
            get {
                return ResourceManager.GetString("SearchFlipQueryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can search by krile query with prefix &quot;?&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchFlipQueryHelp {
            get {
                return ResourceManager.GetString("SearchFlipQueryHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Query is invalid:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchFlipQueryInvalid {
            get {
                return ResourceManager.GetString("SearchFlipQueryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Query is valid. Press enter to start searching. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchFlipQueryValid {
            get {
                return ResourceManager.GetString("SearchFlipQueryValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}&apos;s saved keywords:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchFlipSavedKeywordsFormat {
            get {
                return ResourceManager.GetString("SearchFlipSavedKeywordsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show saved keywords when active account is only one. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchFlipSavedKeywordsUnavailable {
            get {
                return ResourceManager.GetString("SearchFlipSavedKeywordsUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search {0} from twitter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchFlipSearchBySavedKeywordFormat {
            get {
                return ResourceManager.GetString("SearchFlipSearchBySavedKeywordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   From local storage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchFlipSearchLocal {
            get {
                return ResourceManager.GetString("SearchFlipSearchLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search tweets from local storage of Krile. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchFlipSearchLocalDesc {
            get {
                return ResourceManager.GetString("SearchFlipSearchLocalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User @ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchFlipSearchScreenName {
            get {
                return ResourceManager.GetString("SearchFlipSearchScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show user who has specified @id. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchFlipSearchScreenNameDesc {
            get {
                return ResourceManager.GetString("SearchFlipSearchScreenNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   From the tab に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchFlipSearchTab {
            get {
                return ResourceManager.GetString("SearchFlipSearchTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search tweets from current tab. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchFlipSearchTabDesc {
            get {
                return ResourceManager.GetString("SearchFlipSearchTabDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   From twitter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchFlipSearchTwitter {
            get {
                return ResourceManager.GetString("SearchFlipSearchTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search tweets from twitter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchFlipSearchTwitterDesc {
            get {
                return ResourceManager.GetString("SearchFlipSearchTwitterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchFlipSearchUser {
            get {
                return ResourceManager.GetString("SearchFlipSearchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search users from twitter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchFlipSearchUserDesc {
            get {
                return ResourceManager.GetString("SearchFlipSearchUserDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Block に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserInfoBlock {
            get {
                return ResourceManager.GetString("UserInfoBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Report as spam に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserInfoReportAsSpam {
            get {
                return ResourceManager.GetString("UserInfoReportAsSpam", resourceCulture);
            }
        }
    }
}
