//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarryEyes.Globalization.WindowParts {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingFlipResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingFlipResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarryEyes.Globalization.WindowParts.SettingFlipResources", typeof(SettingFlipResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add New Account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountAdd {
            get {
                return ResourceManager.GetString("AccountAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Reset custom API key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountButtonResetKey {
            get {
                return ResourceManager.GetString("AccountButtonResetKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Set custom API key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountButtonSetKey {
            get {
                return ResourceManager.GetString("AccountButtonSetKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use &amp;default key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountButtonUseDefaultKey {
            get {
                return ResourceManager.GetString("AccountButtonUseDefaultKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete This Account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountDelete {
            get {
                return ResourceManager.GetString("AccountDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drag and drop icon to change order of accounts. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountDragDropToChangeOrder {
            get {
                return ResourceManager.GetString("AccountDragDropToChangeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fallback favorites に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountFavoriteFallback {
            get {
                return ResourceManager.GetString("AccountFavoriteFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You should register API keys for use more accounts. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountLimitContent {
            get {
                return ResourceManager.GetString("AccountLimitContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All accounts will be unregistered after registering api key. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountLimitFooter {
            get {
                return ResourceManager.GetString("AccountLimitFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reaching limit of accounts. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountLimitInst {
            get {
                return ResourceManager.GetString("AccountLimitInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Limitation of authentication に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountLimitTitle {
            get {
                return ResourceManager.GetString("AccountLimitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set sensitive flag to uploading media に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountMarkMediaSensitive {
            get {
                return ResourceManager.GetString("AccountMarkMediaSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fallback when POST limited に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountPostFallback {
            get {
                return ResourceManager.GetString("AccountPostFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receive others activities に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountReceiveFollowingsActivity {
            get {
                return ResourceManager.GetString("AccountReceiveFollowingsActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receive replies to not followings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountReceiveRepliesAll {
            get {
                return ResourceManager.GetString("AccountReceiveRepliesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset API Key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountResetKey {
            get {
                return ResourceManager.GetString("AccountResetKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resetting API key make unregistering all accounts from Krile.
        ///Continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountResetKeyContent {
            get {
                return ResourceManager.GetString("AccountResetKeyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset API keys に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountResetKeyTitle {
            get {
                return ResourceManager.GetString("AccountResetKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting API key make unregistering all accounts from Krile.
        ///Continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountSetKeyContent {
            get {
                return ResourceManager.GetString("AccountSetKeyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set API keys に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountSetKeyTitle {
            get {
                return ResourceManager.GetString("AccountSetKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All accounts will be unregistered from Krile. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountSetResetKeyInst {
            get {
                return ResourceManager.GetString("AccountSetResetKeyInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can not receive this account&apos;s timeline nor post from this account. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountUnauthorizeContent {
            get {
                return ResourceManager.GetString("AccountUnauthorizeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In order to unauthorize completely, it is necessary to revoke the right to access from the application management page of a Twitter official site. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountUnauthorizeFooter {
            get {
                return ResourceManager.GetString("AccountUnauthorizeFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you unauthorize {0} from Krile? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountUnauthorizeInstFormat {
            get {
                return ResourceManager.GetString("AccountUnauthorizeInstFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountUnauthorizeTitle {
            get {
                return ResourceManager.GetString("AccountUnauthorizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receive tweets in real-time [recommended] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountUseUserStreams {
            get {
                return ResourceManager.GetString("AccountUseUserStreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About Krile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryAbout {
            get {
                return ResourceManager.GetString("CategoryAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accounts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryAccount {
            get {
                return ResourceManager.GetString("CategoryAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   High-Level Config に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryHighLevel {
            get {
                return ResourceManager.GetString("CategoryHighLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryInput {
            get {
                return ResourceManager.GetString("CategoryInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key Assign に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryKeyAssign {
            get {
                return ResourceManager.GetString("CategoryKeyAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mutes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryMute {
            get {
                return ResourceManager.GetString("CategoryMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notify and Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryNotifyConfirm {
            get {
                return ResourceManager.GetString("CategoryNotifyConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Proxy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryProxy {
            get {
                return ResourceManager.GetString("CategoryProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Theme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryTheme {
            get {
                return ResourceManager.GetString("CategoryTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Third Services に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryThirdService {
            get {
                return ResourceManager.GetString("CategoryThirdService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeline に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryTimeline {
            get {
                return ResourceManager.GetString("CategoryTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply unstable patch [krile may become unstable by auto-updating] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HighApplyUnstablePatch {
            get {
                return ResourceManager.GetString("HighApplyUnstablePatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Below configurations are targeting power users. How behavior of Krile is changed by each property, should read source codes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HighDescription {
            get {
                return ResourceManager.GetString("HighDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable geolocation service [this property may be changed by automatically] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HighDisableGeolocationService {
            get {
                return ResourceManager.GetString("HighDisableGeolocationService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Event display time: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HighEventDisplayDuration {
            get {
                return ResourceManager.GetString("HighEventDisplayDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max (msec): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HighEventDisplayMax {
            get {
                return ResourceManager.GetString("HighEventDisplayMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Min (msec): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HighEventDisplayMin {
            get {
                return ResourceManager.GetString("HighEventDisplayMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load unsigned plugin from development folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HighLoadDeveloperPlugin {
            get {
                return ResourceManager.GetString("HighLoadDeveloperPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log krile&apos;s behaviors [Krile will be slow down] [need to restart] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HighLogKrileBehavior {
            get {
                return ResourceManager.GetString("HighLogKrileBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Optimizing database or delete settings/database. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HighMaintenanceModeDescription {
            get {
                return ResourceManager.GetString("HighMaintenanceModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Post limit parameter: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HighPostLimitParameter {
            get {
                return ResourceManager.GetString("HighPostLimitParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweets per window: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HighPostTweetsPerWindow {
            get {
                return ResourceManager.GetString("HighPostTweetsPerWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window time (sec): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HighPostWindowTime {
            get {
                return ResourceManager.GetString("HighPostWindowTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   REST API receive interval に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HighRestApiInterval {
            get {
                return ResourceManager.GetString("HighRestApiInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restart krile as maintenance mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HighRestartAsMaintenanceMode {
            get {
                return ResourceManager.GetString("HighRestartAsMaintenanceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List Timeline: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HighRestListInterval {
            get {
                return ResourceManager.GetString("HighRestListInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Relation: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HighRestRelationInterval {
            get {
                return ResourceManager.GetString("HighRestRelationInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Timeline: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HighRestSearchInterval {
            get {
                return ResourceManager.GetString("HighRestSearchInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home timeline: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HighRestTimelineInterval {
            get {
                return ResourceManager.GetString("HighRestTimelineInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User info: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HighRestUserInfoInterval {
            get {
                return ResourceManager.GetString("HighRestUserInfoInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Locale code of query for searching twitter: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HighSearchLocale {
            get {
                return ResourceManager.GetString("HighSearchLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use in-memory database mode [need restarting Krile for apply] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HighUseInMemoryDatabase {
            get {
                return ResourceManager.GetString("HighUseInMemoryDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When sending a reply to the reply to the account which is fall back from other account, falling back agency account is specified automatically. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputBacktrackDescription {
            get {
                return ResourceManager.GetString("InputBacktrackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backtrack fallbacked account when reply に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputBacktrackFallback {
            get {
                return ResourceManager.GetString("InputBacktrackFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Closing tweet box:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputCloseAction {
            get {
                return ResourceManager.GetString("InputCloseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm stashing or not に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputCloseConfirm {
            get {
                return ResourceManager.GetString("InputCloseConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Destroy immediately に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputCloseDestroy {
            get {
                return ResourceManager.GetString("InputCloseDestroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save into stash に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputCloseStash {
            get {
                return ResourceManager.GetString("InputCloseStash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open stashed text automaticaly if exists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputRestorePreviousStashed {
            get {
                return ResourceManager.GetString("InputRestorePreviousStashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable input-suggestion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputSuggestEnabled {
            get {
                return ResourceManager.GetString("InputSuggestEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore bound tags when replying someone に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputSuppressTagBindInReply {
            get {
                return ResourceManager.GetString("InputSuppressTagBindInReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All users に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputUserSuggestAll {
            get {
                return ResourceManager.GetString("InputUserSuggestAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Followings only に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputUserSuggestFollowingsOnly {
            get {
                return ResourceManager.GetString("InputUserSuggestFollowingsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Suggestion scope of users: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputUserSuggestMode {
            get {
                return ResourceManager.GetString("InputUserSuggestMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Related users (users follow you or followed from you) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputUserSuggestRelated {
            get {
                return ResourceManager.GetString("InputUserSuggestRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Action: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyAssignAction {
            get {
                return ResourceManager.GetString("KeyAssignAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add new assign に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyAssignAddAssign {
            get {
                return ResourceManager.GetString("KeyAssignAddAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Argument: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyAssignArgument {
            get {
                return ResourceManager.GetString("KeyAssignArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   no argument に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyAssignArgumentNone {
            get {
                return ResourceManager.GetString("KeyAssignArgumentNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   argument optional に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyAssignArgumentOptional {
            get {
                return ResourceManager.GetString("KeyAssignArgumentOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   argument required に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyAssignArgumentRequired {
            get {
                return ResourceManager.GetString("KeyAssignArgumentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configured Assigns: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyAssignCurrentAssign {
            get {
                return ResourceManager.GetString("KeyAssignCurrentAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete this key assigns に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyAssignDelete {
            get {
                return ResourceManager.GetString("KeyAssignDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete selected assign に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyAssignDeleteAssign {
            get {
                return ResourceManager.GetString("KeyAssignDeleteAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete {0}.
        ///Are you sure? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyAssignDeleteContentFormat {
            get {
                return ResourceManager.GetString("KeyAssignDeleteContentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File could not be deleted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyAssignDeleteFailedInst {
            get {
                return ResourceManager.GetString("KeyAssignDeleteFailedInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deletion failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyAssignDeleteFailedTitle {
            get {
                return ResourceManager.GetString("KeyAssignDeleteFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleting key assign. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyAssignDeleteInst {
            get {
                return ResourceManager.GetString("KeyAssignDeleteInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete key assign file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyAssignDeleteTitle {
            get {
                return ResourceManager.GetString("KeyAssignDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Group: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyAssignGroup {
            get {
                return ResourceManager.GetString("KeyAssignGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyAssignKey {
            get {
                return ResourceManager.GetString("KeyAssignKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create new key assigns に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyAssignNew {
            get {
                return ResourceManager.GetString("KeyAssignNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Using key assign: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyAssignUsingAssign {
            get {
                return ResourceManager.GetString("KeyAssignUsingAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mute blocking users [recommended] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MuteBlockingUsers {
            get {
                return ResourceManager.GetString("MuteBlockingUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The following configurations make mute tweets which is undisplayed at Twitter Web.
        ///We recommend be checked, as long as there is no special reason. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MuteDetailDescription {
            get {
                return ResourceManager.GetString("MuteDetailDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detail settings of mutes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MuteDetailSettings {
            get {
                return ResourceManager.GetString("MuteDetailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit mute query に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MuteHeader {
            get {
                return ResourceManager.GetString("MuteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It will cause very-slow timeline construction when use complicated mute filter such as regex.
        ///When lightweight-mute is enabled, muted tweets will not be recorded into database. This will lead to improve speed of timeline construction.
        ///But, some limitations will be applied.
        ///* Mute filter is not applied immediately. Each tweets are filtered once when received.
        ///* Muted tweets will not appear even if mute predicate is changed.
        ///You should clear database file when setting is changed.
        ///Blocked users or no-ret [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MuteLightweightMuteDescription {
            get {
                return ResourceManager.GetString("MuteLightweightMuteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mute no retweets [recommended] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MuteNoRetweets {
            get {
                return ResourceManager.GetString("MuteNoRetweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mute users you specified on twitter official [recommended] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MuteOfficialMutedUsers {
            get {
                return ResourceManager.GetString("MuteOfficialMutedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset changes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MuteReset {
            get {
                return ResourceManager.GetString("MuteReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Lightweight mute [FOR POWER USER] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MuteUseLightweightMute {
            get {
                return ResourceManager.GetString("MuteUseLightweightMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New tweet notification in all tabs are disabled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyAllTabDisabledInst {
            get {
                return ResourceManager.GetString("NotifyAllTabDisabledInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable notifications に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyAllTabDisabledTitle {
            get {
                return ResourceManager.GetString("NotifyAllTabDisabledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notify backfilled tweets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyBackfilledTweets {
            get {
                return ResourceManager.GetString("NotifyBackfilledTweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm on exit application に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyConfirmOnExit {
            get {
                return ResourceManager.GetString("NotifyConfirmOnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turn off new tweet notification in all tabs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyDisableNotifyAllTabs {
            get {
                return ResourceManager.GetString("NotifyDisableNotifyAllTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification Display に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyDisplay {
            get {
                return ResourceManager.GetString("NotifyDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notify my tweets are favorited に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyFavorites {
            get {
                return ResourceManager.GetString("NotifyFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main Display (default) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyMainDisplay {
            get {
                return ResourceManager.GetString("NotifyMainDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notify direct messages for me に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyNewDirectMessages {
            get {
                return ResourceManager.GetString("NotifyNewDirectMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notify new followers of me に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyNewFollowers {
            get {
                return ResourceManager.GetString("NotifyNewFollowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notify mentions for me に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyNewReplies {
            get {
                return ResourceManager.GetString("NotifyNewReplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification of new tweets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyNewTweets {
            get {
                return ResourceManager.GetString("NotifyNewTweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notify my tweets are retweeted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyRetweets {
            get {
                return ResourceManager.GetString("NotifyRetweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show message when post is failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyShowMessageOnTweetFailed {
            get {
                return ResourceManager.GetString("NotifyShowMessageOnTweetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show popup notification when window is active に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyShowPopupWhenWindowIsActive {
            get {
                return ResourceManager.GetString("NotifyShowPopupWhenWindowIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyStyleNone {
            get {
                return ResourceManager.GetString("NotifyStyleNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Popup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyStylePopup {
            get {
                return ResourceManager.GetString("NotifyStylePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slim に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyStyleSlim {
            get {
                return ResourceManager.GetString("NotifyStyleSlim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification Style に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyStyleType {
            get {
                return ResourceManager.GetString("NotifyStyleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification of new tweets can set on each tab. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyToggleParTabsDescription {
            get {
                return ResourceManager.GetString("NotifyToggleParTabsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warn when amending tweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyWarnAmending {
            get {
                return ResourceManager.GetString("NotifyWarnAmending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warn replying if posting account is not replied account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyWarnReplyFromThirdAccount {
            get {
                return ResourceManager.GetString("NotifyWarnReplyFromThirdAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API Proxy (empty for not use): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProxyApiProxy {
            get {
                return ResourceManager.GetString("ProxyApiProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bypass host list (separated by line): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProxyBypassList {
            get {
                return ResourceManager.GetString("ProxyBypassList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bypass localhost に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProxyBypassLocal {
            get {
                return ResourceManager.GetString("ProxyBypassLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Host: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProxyDetailHost {
            get {
                return ResourceManager.GetString("ProxyDetailHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProxyDetailPort {
            get {
                return ResourceManager.GetString("ProxyDetailPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Web proxy configuration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProxyDetailSettings {
            get {
                return ResourceManager.GetString("ProxyDetailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Web Proxy: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProxyWebProxy {
            get {
                return ResourceManager.GetString("ProxyWebProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify using proxy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProxyWebProxyExplicit {
            get {
                return ResourceManager.GetString("ProxyWebProxyExplicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Internet Explorer&apos;s configuration (sometimes posting tweets take more seconds) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProxyWebProxyIE {
            get {
                return ResourceManager.GetString("ProxyWebProxyIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do not use proxy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProxyWebProxyNone {
            get {
                return ResourceManager.GetString("ProxyWebProxyNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open theme folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThemeOpenFolder {
            get {
                return ResourceManager.GetString("ThemeOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThemeOpenPictureFilter {
            get {
                return ResourceManager.GetString("ThemeOpenPictureFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select wallpaper image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThemeOpenPictureTitle {
            get {
                return ResourceManager.GetString("ThemeOpenPictureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Using theme: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThemeUsingTheme {
            get {
                return ResourceManager.GetString("ThemeUsingTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeline wallpaper: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThemeWallpaperFile {
            get {
                return ResourceManager.GetString("ThemeWallpaperFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wallpaper transparency: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThemeWallpaperTransparency {
            get {
                return ResourceManager.GetString("ThemeWallpaperTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Browser path (empty for use default): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThirdBrowserPath {
            get {
                return ResourceManager.GetString("ThirdBrowserPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allow favorite myself に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineAllowFavoriteMyself {
            get {
                return ResourceManager.GetString("TimelineAllowFavoriteMyself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Animate to show new tweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineAnimateNewTweet {
            get {
                return ResourceManager.GetString("TimelineAnimateNewTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto cleanup old tweets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineAutoCleanup {
            get {
                return ResourceManager.GetString("TimelineAutoCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Note: Deletion will be performed if a twice as many tweet as this number is stored. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineAutoCleanupDescription {
            get {
                return ResourceManager.GetString("TimelineAutoCleanupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of leaving status:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineAutoCleanupThreshold {
            get {
                return ResourceManager.GetString("TimelineAutoCleanupThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always expanded (default) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineDisplayExpanded {
            get {
                return ResourceManager.GetString("TimelineDisplayExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always shrinked multi line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineDisplayMultiline {
            get {
                return ResourceManager.GetString("TimelineDisplayMultiline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compact multi line (focus to expand) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineDisplayMultiLineMixed {
            get {
                return ResourceManager.GetString("TimelineDisplayMultiLineMixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always single line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineDisplaySingleLine {
            get {
                return ResourceManager.GetString("TimelineDisplaySingleLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single line (focus to expand) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineDisplaySingleLineMixed {
            get {
                return ResourceManager.GetString("TimelineDisplaySingleLineMixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeline Type: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineDisplayType {
            get {
                return ResourceManager.GetString("TimelineDisplayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Larger size (high quality, slower) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineIconQualityHigh {
            get {
                return ResourceManager.GetString("TimelineIconQualityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimum size (poor quality, fast) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineIconQualityMinimum {
            get {
                return ResourceManager.GetString("TimelineIconQualityMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None (displays empty region) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineIconQualityNone {
            get {
                return ResourceManager.GetString("TimelineIconQualityNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Optimized size (good quality, speedy) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineIconQualityOptimized {
            get {
                return ResourceManager.GetString("TimelineIconQualityOptimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Original size (best quality, very slow) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineIconQualityOriginal {
            get {
                return ResourceManager.GetString("TimelineIconQualityOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeline Icon Quality: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineIconQualityType {
            get {
                return ResourceManager.GetString("TimelineIconQualityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open original size when clicked thumbnail of twitter-official picture. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineOpenTwitterPicWithOriginalSize {
            get {
                return ResourceManager.GetString("TimelineOpenTwitterPicWithOriginalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scroll timeline pixel by pixel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineScrollByPixel {
            get {
                return ResourceManager.GetString("TimelineScrollByPixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineScrollLockAlways {
            get {
                return ResourceManager.GetString("TimelineScrollLockAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Explicit (not implemented yet) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineScrollLockExplicit {
            get {
                return ResourceManager.GetString("TimelineScrollLockExplicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When mouse is over に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineScrollLockMouseOver {
            get {
                return ResourceManager.GetString("TimelineScrollLockMouseOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeline Scroll-Lock: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineScrollLockType {
            get {
                return ResourceManager.GetString("TimelineScrollLockType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineScrollLockUnlock {
            get {
                return ResourceManager.GetString("TimelineScrollLockUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When scroll-downed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineScrollLockWhenScrolled {
            get {
                return ResourceManager.GetString("TimelineScrollLockWhenScrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language of searching twitter: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineSearchLanguage {
            get {
                return ResourceManager.GetString("TimelineSearchLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Unknown language: unregistered code or invalid input) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineSearchLanguageInvalid {
            get {
                return ResourceManager.GetString("TimelineSearchLanguageInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unspecified (targets all languages) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineSearchLanguageUnspecified {
            get {
                return ResourceManager.GetString("TimelineSearchLanguageUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show thumbnails of attached images に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineShowThumbnails {
            get {
                return ResourceManager.GetString("TimelineShowThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show all thumbnails に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineThumbnailAll {
            get {
                return ResourceManager.GetString("TimelineThumbnailAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineThumbnailNone {
            get {
                return ResourceManager.GetString("TimelineThumbnailNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show first image only に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineThumbnailSingle {
            get {
                return ResourceManager.GetString("TimelineThumbnailSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thumbnails: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineThumbnailType {
            get {
                return ResourceManager.GetString("TimelineThumbnailType", resourceCulture);
            }
        }
    }
}
