//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarryEyes.Globalization.WindowParts {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VersionInfoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VersionInfoResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarryEyes.Globalization.WindowParts.VersionInfoResources", typeof(VersionInfoResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Development of Krile is continued by contribution and efforts of many people: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DonateLabel {
            get {
                return ResourceManager.GetString("DonateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Development of Krile is continued by contribution and efforts of people including you: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DonateThanksLabel {
            get {
                return ResourceManager.GetString("DonateThanksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update is available. click to auto-install updates. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateAvailableDescription {
            get {
                return ResourceManager.GetString("UpdateAvailableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   update available! (click to install) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateAvailableLabel {
            get {
                return ResourceManager.GetString("UpdateAvailableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are using newest krile. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateLatestDescription {
            get {
                return ResourceManager.GetString("UpdateLatestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   latest version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateLatestLabel {
            get {
                return ResourceManager.GetString("UpdateLatestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now checking updates. please wait... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateRefreshingDescription {
            get {
                return ResourceManager.GetString("UpdateRefreshingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   checking update... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateRefreshingLabel {
            get {
                return ResourceManager.GetString("UpdateRefreshingLabel", resourceCulture);
            }
        }
    }
}
